import fs from 'node:fs';
import path from 'node:path';
const root=process.argv[2]||'release';
const must=(ok,label)=>{if(!ok)throw new Error('Growth QA FAIL: '+label);console.log('Growth QA PASS:',label)};
const app=fs.readFileSync(path.join(root,'netlify/functions/app.mjs'),'utf8');
const admin=fs.readFileSync(path.join(root,'assets/admin.js'),'utf8');
const site=fs.readFileSync(path.join(root,'assets/site.js'),'utf8');
const css=fs.readFileSync(path.join(root,'assets/styles.css'),'utf8');
must(app.includes("path==='/api/cards'"),'public cards API route');
must(app.includes("action==='save_cards'"),'authenticated cards save action');
must(app.includes('RASSMIY_SEED_ARTICLES_V60'),'article seed migration');
must(app.includes('RASSMIY_SEED_PAGES_V60'),'landing page seed migration');
must(admin.includes('__RASSMIY_CARD_MANAGER_V60__'),'card manager UI');
must(site.includes('__RASSMIY_CARDS_V60__'),'frontend card hydration');
must(css.includes('Rassmiy growth system v6.0'),'growth styles');
for(const f of ['index.html','ar/index.html','en/index.html','ar/about.html','en/about.html','ar/services.html','en/services.html','ar/portfolio.html','en/portfolio.html','ar/contact.html','en/contact.html'])must(fs.existsSync(path.join(root,f)),f+' exists');
must(fs.readFileSync(path.join(root,'ar/index.html'),'utf8').includes('GROWTH_HOME_AR_V60'),'Arabic home growth content');
must(fs.readFileSync(path.join(root,'en/index.html'),'utf8').includes('GROWTH_HOME_EN_V60'),'English home growth content');
must(fs.readFileSync(path.join(root,'ar/services.html'),'utf8').includes('GROWTH_SERVICES_AR_V60'),'Arabic services growth content');
must(fs.readFileSync(path.join(root,'ar/portfolio.html'),'utf8').includes('GROWTH_PORT_AR_V60'),'Arabic portfolio growth content');
const meta=JSON.parse(fs.readFileSync(path.join(root,'growth-v60.json'),'utf8'));
must(meta.cards.length>=13,'editable card seeds');
must(meta.pages.length===3,'lead landing page seeds');
must(meta.articles.length===6,'SEO article seeds');
console.log('GROWTH_QA_V60=PASS');
