import fs from 'node:fs';
import path from 'node:path';

const root=process.argv[2]||'release';
const appFile=path.join(root,'netlify','functions','app.mjs');
let app=fs.readFileSync(appFile,'utf8');

const CARDS=[
 {id:'service-seo',collection:'service',order:10,enabled:true,icon:'⌕',image:'',title_ar:'SEO و AEO وظهور العلامة في البحث',title_en:'SEO, AEO & Search Visibility',description_ar:'استراتيجية تقنية ومحتوى وهيكلة تساعد صفحاتك على الظهور في Google ونتائج الذكاء الاصطناعي وتحويل الزيارات إلى فرص أعمال.',description_en:'Technical SEO, content and information architecture designed to earn search visibility and convert qualified traffic into opportunities.',eyebrow_ar:'نمو عضوي',eyebrow_en:'Organic Growth',metric_ar:'بحث → Leads',metric_en:'Search → Leads',cta_label_ar:'ناقش خطة SEO',cta_label_en:'Discuss SEO growth',cta_url_ar:'/ar/pages/استشاري-seo-الرياض',cta_url_en:'/en/pages/seo-consultant-riyadh',alt_ar:'خدمات SEO و AEO في الرياض',alt_en:'SEO and AEO services in Riyadh'},
 {id:'service-paid',collection:'service',order:20,enabled:true,icon:'↗',image:'',title_ar:'Performance Marketing والإعلانات المدفوعة',title_en:'Performance Marketing & Paid Media',description_ar:'هيكلة حملات Google وMeta والمنصات المناسبة حول CAC وROAS وجودة الـLead بدل التركيز على النقرات فقط.',description_en:'Google, Meta and channel strategy structured around CAC, ROAS and lead quality—not clicks alone.',eyebrow_ar:'اكتساب العملاء',eyebrow_en:'Acquisition',metric_ar:'CAC / ROAS',metric_en:'CAC / ROAS',cta_label_ar:'راجع حملاتك',cta_label_en:'Audit your campaigns',cta_url_ar:'/ar/contact.html?service=paid-media',cta_url_en:'/en/contact.html?service=paid-media',alt_ar:'إدارة إعلانات مدفوعة',alt_en:'Paid media management'},
 {id:'service-social',collection:'service',order:30,enabled:true,icon:'◎',image:'',title_ar:'المحتوى والسوشيال ميديا',title_en:'Content & Social Media',description_ar:'نظام محتوى يبني الثقة، يدعم البحث، ويغذي الحملات وقمع التحويل برسائل واضحة لكل مرحلة من رحلة العميل.',description_en:'A content system that builds trust, supports search and feeds campaigns with the right message across the funnel.',eyebrow_ar:'ثقة وطلب',eyebrow_en:'Demand & Trust',metric_ar:'Content → Demand',metric_en:'Content → Demand',cta_label_ar:'ابنِ نظام المحتوى',cta_label_en:'Build your content system',cta_url_ar:'/ar/contact.html?service=content-copywriting',cta_url_en:'/en/contact.html?service=content-copywriting',alt_ar:'استراتيجية محتوى وسوشيال ميديا',alt_en:'Content and social strategy'},
 {id:'service-ecommerce',collection:'service',order:40,enabled:true,icon:'▣',image:'',title_ar:'نمو التجارة الإلكترونية',title_en:'E-Commerce Growth',description_ar:'تحسين المتجر، القياس، صفحات المنتجات، Merchant Center، القنوات الإعلانية وCRO ضمن خطة واحدة تركز على الإيراد.',description_en:'Store UX, analytics, product pages, Merchant Center, paid channels and CRO aligned around revenue growth.',eyebrow_ar:'إيرادات المتجر',eyebrow_en:'Commerce Revenue',metric_ar:'Traffic → Revenue',metric_en:'Traffic → Revenue',cta_label_ar:'خطط لنمو المتجر',cta_label_en:'Plan e-commerce growth',cta_url_ar:'/ar/pages/نمو-المتاجر-الإلكترونية-السعودية',cta_url_en:'/en/pages/ecommerce-growth-saudi-arabia',alt_ar:'استراتيجية نمو المتاجر الإلكترونية',alt_en:'E-commerce growth strategy'},
 {id:'service-content',collection:'service',order:50,enabled:true,icon:'✎',image:'',title_ar:'Copywriting ومحتوى يحوّل',title_en:'Conversion Copy & Content',description_ar:'رسائل صفحات الهبوط، الخدمات، المنتجات والمقالات مبنية على نية البحث واعتراضات العميل وقرار الشراء.',description_en:'Landing-page, service, product and article copy built around search intent, objections and buying decisions.',eyebrow_ar:'رسائل تحويل',eyebrow_en:'Conversion Messaging',metric_ar:'Intent → Action',metric_en:'Intent → Action',cta_label_ar:'طوّر رسالتك',cta_label_en:'Improve your messaging',cta_url_ar:'/ar/contact.html?service=content-copywriting',cta_url_en:'/en/contact.html?service=content-copywriting',alt_ar:'كتابة محتوى تسويقي',alt_en:'Conversion copywriting'},
 {id:'service-events',collection:'service',order:60,enabled:true,icon:'◇',image:'',title_ar:'الفعاليات وتنشيط العلامة',title_en:'Events & Brand Activation',description_ar:'ربط الحدث بهدف تجاري واضح: دعوات، تجربة علامة، محتوى، Leads، متابعة وقياس ما بعد الفعالية.',description_en:'Events tied to a commercial objective: invitations, brand experience, content, lead capture and post-event follow-up.',eyebrow_ar:'Offline → Pipeline',eyebrow_en:'Offline → Pipeline',metric_ar:'Event → Leads',metric_en:'Event → Leads',cta_label_ar:'خطط للفعالية',cta_label_en:'Plan an activation',cta_url_ar:'/ar/contact.html?service=events-activation',cta_url_en:'/en/contact.html?service=events-activation',alt_ar:'إدارة فعاليات وتسويق ميداني',alt_en:'Events and brand activation'},
 {id:'service-analytics',collection:'service',order:70,enabled:true,icon:'◫',image:'',title_ar:'Analytics وMarketing Intelligence',title_en:'Analytics & Marketing Intelligence',description_ar:'لوحات قياس وTracking تربط القناة بالـLead والبيع، وتكشف أين تُهدر الميزانية وأين توجد فرص النمو.',description_en:'Tracking and dashboards that connect channels to leads and revenue, exposing waste and growth opportunities.',eyebrow_ar:'قرارات بالبيانات',eyebrow_en:'Data-led Decisions',metric_ar:'Data → Decisions',metric_en:'Data → Decisions',cta_label_ar:'راجع القياس',cta_label_en:'Review measurement',cta_url_ar:'/ar/contact.html?service=analytics-reporting',cta_url_en:'/en/contact.html?service=analytics-reporting',alt_ar:'تحليلات التسويق وقياس الأداء',alt_en:'Marketing analytics and measurement'},
 {id:'case-ecommerce',collection:'portfolio',order:10,enabled:true,icon:'',image:'',title_ar:'منظومة نمو لمتجر إلكتروني',title_en:'E-Commerce Growth System',description_ar:'ربط تجربة المتجر وSEO وMerchant Center وTracking والإعلانات في مسار واحد يركز على التحويل والإيراد.',description_en:'Connected store UX, SEO, Merchant Center, tracking and paid media into one revenue-focused growth system.',eyebrow_ar:'E-Commerce',eyebrow_en:'E-Commerce',metric_ar:'من الزيارة إلى الطلب',metric_en:'Visit → Order',cta_label_ar:'ناقش مشروعًا مشابهًا',cta_label_en:'Discuss a similar project',cta_url_ar:'https://wa.me/966536741442?text=مرحباً%20محمد،%20أرغب%20في%20مناقشة%20مشروع%20تجارة%20إلكترونية',cta_url_en:'https://wa.me/966536741442?text=Hi%20Mohamed%2C%20I%20want%20to%20discuss%20an%20e-commerce%20growth%20project',alt_ar:'مشروع نمو متجر إلكتروني',alt_en:'E-commerce growth case'},
 {id:'case-seo',collection:'portfolio',order:20,enabled:true,icon:'',image:'',title_ar:'SEO ومحتوى لبناء الطلب العضوي',title_en:'SEO & Content for Organic Demand',description_ar:'هيكلة موضوعات وصفحات تربط الكلمات التجارية بالمحتوى المعلوماتي وتبني مسارات داخلية تقود لطلب الخدمة.',description_en:'Built topic and page architecture that connects commercial queries with educational content and lead paths.',eyebrow_ar:'SEO',eyebrow_en:'SEO',metric_ar:'Visibility → Leads',metric_en:'Visibility → Leads',cta_label_ar:'ناقش مشروع SEO',cta_label_en:'Discuss an SEO project',cta_url_ar:'https://wa.me/966536741442?text=مرحباً%20محمد،%20أرغب%20في%20مناقشة%20مشروع%20SEO',cta_url_en:'https://wa.me/966536741442?text=Hi%20Mohamed%2C%20I%20want%20to%20discuss%20an%20SEO%20project',alt_ar:'دراسة حالة SEO',alt_en:'SEO case study'},
 {id:'case-paid',collection:'portfolio',order:30,enabled:true,icon:'',image:'',title_ar:'إعادة هيكلة Paid Media حول الربحية',title_en:'Paid Media Built Around Profitability',description_ar:'فصل الحملات حسب النية والمرحلة، وضبط القياس والرسائل والميزانية بناءً على جودة التحويل لا حجم الزيارات.',description_en:'Separated campaigns by intent and funnel stage, aligning measurement, creative and spend to conversion quality.',eyebrow_ar:'Performance',eyebrow_en:'Performance',metric_ar:'Spend → Outcome',metric_en:'Spend → Outcome',cta_label_ar:'راجع حملاتك',cta_label_en:'Review your campaigns',cta_url_ar:'https://wa.me/966536741442?text=مرحباً%20محمد،%20أرغب%20في%20مراجعة%20حملات%20الإعلانات',cta_url_en:'https://wa.me/966536741442?text=Hi%20Mohamed%2C%20I%20want%20a%20paid%20media%20audit',alt_ar:'دراسة حالة إعلانات مدفوعة',alt_en:'Paid media case study'},
 {id:'case-events',collection:'portfolio',order:40,enabled:true,icon:'',image:'',title_ar:'إطلاق علامة وفعالية قابلة للقياس',title_en:'Measurable Brand Launch & Event',description_ar:'تنسيق الرسائل والمواد والتجربة والدعوات والمتابعة بحيث تتحول الفعالية من نشاط منفصل إلى أصل تسويقي قابل للقياس.',description_en:'Aligned messaging, materials, experience, invitations and follow-up so the event becomes a measurable marketing asset.',eyebrow_ar:'Activation',eyebrow_en:'Activation',metric_ar:'Event → Pipeline',metric_en:'Event → Pipeline',cta_label_ar:'خطط لفعالية',cta_label_en:'Plan an event',cta_url_ar:'https://wa.me/966536741442?text=مرحباً%20محمد،%20أرغب%20في%20مناقشة%20فعالية%20أو%20إطلاق%20علامة',cta_url_en:'https://wa.me/966536741442?text=Hi%20Mohamed%2C%20I%20want%20to%20discuss%20a%20brand%20event',alt_ar:'إطلاق علامة وفعالية',alt_en:'Brand launch event case'},
 {id:'case-brand',collection:'portfolio',order:50,enabled:true,icon:'',image:'',title_ar:'كتالوجات وهوية ومواد مبيعات',title_en:'Catalogues, Brand & Sales Materials',description_ar:'تحويل مواد التسويق من تصميمات منفصلة إلى أدوات بيع متسقة تساعد الفريق التجاري على شرح القيمة بسرعة.',description_en:'Turned scattered marketing assets into consistent sales tools that help commercial teams communicate value faster.',eyebrow_ar:'Sales Enablement',eyebrow_en:'Sales Enablement',metric_ar:'Brand → Sales',metric_en:'Brand → Sales',cta_label_ar:'ناقش مواد المبيعات',cta_label_en:'Discuss sales materials',cta_url_ar:'/ar/contact.html',cta_url_en:'/en/contact.html',alt_ar:'مواد تسويق ومبيعات',alt_en:'Marketing and sales materials'},
 {id:'case-education',collection:'portfolio',order:60,enabled:true,icon:'',image:'',title_ar:'تسويق رقمي لخدمات تعليمية',title_en:'Digital Marketing for Education',description_ar:'صياغة عرض القيمة، صفحات التحويل، المحتوى والحملات حول نية المتقدم ومرحلة القرار بدل النشر العام.',description_en:'Aligned value proposition, landing pages, content and campaigns to applicant intent and decision stage.',eyebrow_ar:'Lead Generation',eyebrow_en:'Lead Generation',metric_ar:'Interest → Enquiry',metric_en:'Interest → Enquiry',cta_label_ar:'ناقش مشروع Leads',cta_label_en:'Discuss lead generation',cta_url_ar:'/ar/contact.html',cta_url_en:'/en/contact.html',alt_ar:'تسويق خدمات تعليمية',alt_en:'Education marketing'}
];

const PAGES=[
 {
  id:'seed-page-seo-riyadh',translation_mode:'bilingual',lang:'ar',status:'published',robots_index:true,robots_follow:true,show_in_nav:false,nav_order:90,
  title:'استشاري SEO في الرياض',title_ar:'استشاري SEO في الرياض',title_en:'SEO Consultant in Riyadh',
  slug:'seo-consultant-riyadh',slug_ar:'استشاري-seo-الرياض',slug_en:'seo-consultant-riyadh',
  short_description:'استشارات SEO وAEO عملية للشركات في الرياض والسعودية.',short_description_ar:'استشارات SEO وAEO عملية للشركات في الرياض والسعودية لزيادة الظهور والطلب العضوي وتحويل البحث إلى فرص أعمال.',short_description_en:'Practical SEO and AEO consulting for Riyadh and Saudi businesses focused on visibility, qualified demand and conversion.',
  seo_title:'استشاري SEO في الرياض | Rassmiy Marketing',seo_title_ar:'استشاري SEO في الرياض | استراتيجية ونمو عضوي',seo_title_en:'SEO Consultant in Riyadh | Organic Growth Strategy',
  meta_description:'استشاري SEO في الرياض للشركات التي تحتاج استراتيجية تقنية ومحتوى وقياس تربط الظهور بالعملاء المحتملين.',meta_description_ar:'استشاري SEO في الرياض للشركات التي تحتاج استراتيجية تقنية ومحتوى وقياس تربط الظهور بالعملاء المحتملين.',meta_description_en:'SEO consultant in Riyadh for businesses that need technical SEO, content strategy and measurement tied to qualified leads.',
  focus_keyword:'استشاري SEO في الرياض',focus_keyword_ar:'استشاري SEO في الرياض',focus_keyword_en:'SEO consultant Riyadh',
  secondary_keywords:'شركة SEO الرياض, تحسين محركات البحث السعودية',secondary_keywords_ar:'شركة SEO الرياض, تحسين محركات البحث السعودية, استشارات SEO',secondary_keywords_en:'SEO services Riyadh, SEO Saudi Arabia, technical SEO consultant',
  content_ar:`<h2>SEO ليس ترتيب كلمات فقط؛ هو قناة طلب قابلة للقياس</h2><p>إذا كان موقعك يحصل على زيارات بدون فرص بيع، أو لا يظهر أمام العملاء الذين يبحثون عن خدماتك، فالمشكلة غالبًا ليست في كتابة مقالات أكثر. المطلوب هو ربط البنية التقنية، نية البحث، الصفحات التجارية، المحتوى، الروابط الداخلية والقياس ضمن نظام واحد.</p><h2>ماذا يشمل العمل؟</h2><ul><li>Technical SEO وفحص الفهرسة والزحف.</li><li>خريطة كلمات مرتبطة بنية الشراء والـfunnel.</li><li>هيكلة صفحات الخدمات والـLanding Pages.</li><li>Content Clusters تدعم الصفحات التجارية.</li><li>AEO/GEO لزيادة قابلية الاستشهاد بالمحتوى في نتائج الذكاء الاصطناعي.</li><li>قياس Leads وليس الزيارات فقط.</li></ul><h2>لمن تناسب الخدمة؟</h2><p>للشركات في الرياض والسعودية التي لديها خدمة أو منتج واضح وتريد أن يتحول البحث إلى قناة نمو مستمرة بدل الاعتماد الكامل على الإعلانات.</p><h2>طريقة العمل</h2><p>Audit → Opportunity Map → Priorities → Execution Roadmap → Measurement. تبدأ الخطة بأعلى فرص الأثر التجاري، لا بقائمة طويلة من التوصيات العامة.</p><h2>هل تحتاج مراجعة SEO؟</h2><p><a href="/ar/contact.html?service=seo-aeo">اطلب مراجعة أولية للموقع</a> وسنحدد أين يوجد أكبر تسرب في الظهور أو التحويل.</p>`,
  content_en:`<h2>SEO is not a rankings project; it is a measurable demand channel</h2><p>If your site gets traffic without enquiries—or fails to appear when buyers search for your services—the answer is rarely “publish more articles.” The real work is connecting technical health, intent, commercial pages, content, internal linking and measurement.</p><h2>What the engagement covers</h2><ul><li>Technical SEO, crawlability and indexation.</li><li>Keyword and intent mapping across the funnel.</li><li>Service and landing-page architecture.</li><li>Content clusters that strengthen commercial pages.</li><li>AEO/GEO to improve AI-search discoverability.</li><li>Lead and conversion measurement, not traffic alone.</li></ul><h2>Who it is for</h2><p>Riyadh and Saudi businesses with a clear offer that want organic search to become a repeatable growth channel rather than relying entirely on paid acquisition.</p><h2>How I work</h2><p>Audit → Opportunity Map → Priorities → Execution Roadmap → Measurement. The roadmap starts with the highest commercial-impact opportunities.</p><h2>Need an SEO review?</h2><p><a href="/en/contact.html?service=seo-aeo">Request an initial review</a> and we can identify where visibility or conversion is leaking.</p>`,
  og_title_ar:'استشاري SEO في الرياض',og_title_en:'SEO Consultant in Riyadh',og_description_ar:'SEO وAEO للشركات في الرياض والسعودية.',og_description_en:'SEO and AEO consulting for Riyadh and Saudi businesses.',og_image_ar:'',og_image_en:'',canonical_url_ar:'',canonical_url_en:'',schema_type:'ProfessionalService',schema_type_ar:'ProfessionalService',schema_type_en:'ProfessionalService',schema_json:'',schema_json_ar:'',schema_json_en:'',created_at:'2026-10-04T00:00:00.000Z',updated_at:'2026-10-04T00:00:00.000Z'
 },
 {
  id:'seed-page-digital-marketing-riyadh',translation_mode:'bilingual',lang:'ar',status:'published',robots_index:true,robots_follow:true,show_in_nav:false,nav_order:91,
  title:'استشاري تسويق رقمي في الرياض',title_ar:'استشاري تسويق رقمي في الرياض',title_en:'Digital Marketing Consultant in Riyadh',
  slug:'digital-marketing-consultant-riyadh',slug_ar:'استشاري-تسويق-رقمي-الرياض',slug_en:'digital-marketing-consultant-riyadh',
  short_description_ar:'استراتيجية تسويق رقمي متكاملة تربط SEO والإعلانات والمحتوى والتجارة الإلكترونية بالـLeads والإيراد.',short_description_en:'Integrated digital marketing strategy connecting SEO, paid media, content and e-commerce to leads and revenue.',
  short_description:'استراتيجية تسويق رقمي متكاملة للشركات في الرياض.',
  seo_title_ar:'استشاري تسويق رقمي في الرياض | استراتيجية متكاملة',seo_title_en:'Digital Marketing Consultant Riyadh | Integrated Growth',seo_title:'استشاري تسويق رقمي في الرياض',
  meta_description_ar:'استشاري تسويق رقمي في الرياض لتوحيد SEO والإعلانات والمحتوى والتحليلات في خطة نمو قابلة للقياس.',meta_description_en:'Digital marketing consultant in Riyadh aligning SEO, paid media, content and analytics into a measurable growth plan.',meta_description:'استشاري تسويق رقمي في الرياض.',
  focus_keyword_ar:'استشاري تسويق رقمي في الرياض',focus_keyword_en:'digital marketing consultant Riyadh',focus_keyword:'استشاري تسويق رقمي في الرياض',
  secondary_keywords_ar:'استراتيجية تسويق رقمي السعودية, مستشار تسويق الرياض',secondary_keywords_en:'digital marketing strategy Saudi Arabia, marketing consultant Riyadh',secondary_keywords:'استراتيجية تسويق رقمي السعودية',
  content_ar:`<h2>حين تعمل القنوات منفصلة، تضيع الميزانية بين الفرق والمنصات</h2><p>التسويق المتكامل يبدأ من هدف تجاري واحد ثم يوزع الأدوار بين SEO والإعلانات والمحتوى والسوشيال والتجارة الإلكترونية والفعاليات والتحليلات.</p><h2>ما الذي تحصل عليه؟</h2><ul><li>تشخيص القنوات والـfunnel الحالي.</li><li>تحديد ICP ورسائل القيمة والاعتراضات.</li><li>خطة 90 يومًا بأولويات واضحة.</li><li>Media mix وContent system وSEO roadmap.</li><li>Tracking وDashboard تربط النشاط بالنتيجة.</li></ul><h2>النتيجة المطلوبة</h2><p>تقليل الأعمال المتفرقة، تحسين جودة القرارات، وتوجيه الوقت والميزانية إلى القنوات التي تخدم الـPipeline أو الإيراد.</p><p><a href="/ar/contact.html">اطلب جلسة تشخيص تسويقي</a>.</p>`,
  content_en:`<h2>When channels operate in silos, budget gets lost between teams and platforms</h2><p>An integrated marketing system starts with one commercial objective and assigns clear roles to SEO, paid media, content, social, e-commerce, events and analytics.</p><h2>What you get</h2><ul><li>Channel and funnel diagnosis.</li><li>ICP, value proposition and objection mapping.</li><li>A prioritised 90-day plan.</li><li>Media mix, content system and SEO roadmap.</li><li>Tracking and dashboards tied to outcomes.</li></ul><h2>The goal</h2><p>Reduce fragmented activity, improve decision quality and direct time and budget toward channels that contribute to pipeline or revenue.</p><p><a href="/en/contact.html">Request a marketing diagnosis session</a>.</p>`,
  og_title_ar:'استشاري تسويق رقمي في الرياض',og_title_en:'Digital Marketing Consultant in Riyadh',og_description_ar:'خطة تسويق متكاملة تربط القنوات بالنتائج.',og_description_en:'Integrated marketing planning tied to commercial outcomes.',og_image_ar:'',og_image_en:'',canonical_url_ar:'',canonical_url_en:'',schema_type:'ProfessionalService',schema_type_ar:'ProfessionalService',schema_type_en:'ProfessionalService',schema_json:'',schema_json_ar:'',schema_json_en:'',created_at:'2026-10-04T00:00:00.000Z',updated_at:'2026-10-04T00:00:00.000Z'
 },
 {
  id:'seed-page-ecommerce-growth',translation_mode:'bilingual',lang:'ar',status:'published',robots_index:true,robots_follow:true,show_in_nav:false,nav_order:92,
  title:'نمو المتاجر الإلكترونية في السعودية',title_ar:'نمو المتاجر الإلكترونية في السعودية',title_en:'E-Commerce Growth in Saudi Arabia',
  slug:'ecommerce-growth-saudi-arabia',slug_ar:'نمو-المتاجر-الإلكترونية-السعودية',slug_en:'ecommerce-growth-saudi-arabia',
  short_description_ar:'استراتيجية نمو للمتاجر تربط الزيارات بالتجربة والقياس والتحويل والإيراد.',short_description_en:'E-commerce growth strategy connecting traffic, UX, measurement, conversion and revenue.',short_description:'استراتيجية نمو للمتاجر الإلكترونية في السعودية.',
  seo_title_ar:'نمو المتاجر الإلكترونية في السعودية | CRO وSEO وإعلانات',seo_title_en:'E-Commerce Growth Saudi Arabia | CRO, SEO & Paid Media',seo_title:'نمو المتاجر الإلكترونية في السعودية',
  meta_description_ar:'خطة نمو للمتاجر الإلكترونية في السعودية تشمل CRO وSEO وMerchant Center وTracking والإعلانات وصفحات المنتجات.',meta_description_en:'E-commerce growth in Saudi Arabia across CRO, SEO, Merchant Center, tracking, product pages and paid media.',meta_description:'نمو المتاجر الإلكترونية في السعودية.',
  focus_keyword_ar:'نمو المتاجر الإلكترونية في السعودية',focus_keyword_en:'ecommerce growth Saudi Arabia',focus_keyword:'نمو المتاجر الإلكترونية في السعودية',
  secondary_keywords_ar:'تسويق متجر إلكتروني, CRO السعودية, SEO متجر إلكتروني',secondary_keywords_en:'ecommerce marketing Saudi Arabia, CRO Saudi Arabia, ecommerce SEO',secondary_keywords:'تسويق متجر إلكتروني',
  content_ar:`<h2>المشكلة ليست دائمًا في جلب زيارات أكثر</h2><p>كثير من المتاجر تخسر النمو بين صفحة المنتج والدفع، أو بسبب قياس ناقص، أو Feed ضعيف، أو رسائل إعلانية لا تطابق نية العميل.</p><h2>منظومة النمو</h2><ul><li>تحليل مصادر الزيارات وربحية القنوات.</li><li>CRO لصفحات التصنيف والمنتج والسلة والدفع.</li><li>SEO للمنتجات والفئات وربط المحتوى بالطلب.</li><li>Merchant Center وFeeds وجودة البيانات.</li><li>Tracking للأحداث والتحويلات والقيمة.</li><li>Retention وRepeat Purchase حيث يناسب نموذج العمل.</li></ul><h2>الأولوية</h2><p>نبدأ من أكبر نقطة تسرب في الإيراد، لا من قناة جديدة فقط.</p><p><a href="/ar/contact.html?service=ecommerce-growth">اطلب مراجعة لنمو المتجر</a>.</p>`,
  content_en:`<h2>More traffic is not always the growth constraint</h2><p>Many stores lose revenue between product discovery and checkout because of weak UX, incomplete tracking, poor feeds or ad messages that do not match customer intent.</p><h2>The growth system</h2><ul><li>Traffic-source and channel profitability analysis.</li><li>CRO across category, product, cart and checkout.</li><li>Product/category SEO and demand-driven content.</li><li>Merchant Center, feeds and data quality.</li><li>Event, conversion and value tracking.</li><li>Retention and repeat purchase where relevant.</li></ul><h2>Priority first</h2><p>The roadmap starts with the largest revenue leak—not simply another acquisition channel.</p><p><a href="/en/contact.html?service=ecommerce-growth">Request an e-commerce growth review</a>.</p>`,
  og_title_ar:'نمو المتاجر الإلكترونية في السعودية',og_title_en:'E-Commerce Growth in Saudi Arabia',og_description_ar:'CRO وSEO وTracking وإعلانات ضمن منظومة واحدة.',og_description_en:'CRO, SEO, tracking and paid media in one growth system.',og_image_ar:'',og_image_en:'',canonical_url_ar:'',canonical_url_en:'',schema_type:'Service',schema_type_ar:'Service',schema_type_en:'Service',schema_json:'',schema_json_ar:'',schema_json_en:'',created_at:'2026-10-04T00:00:00.000Z',updated_at:'2026-10-04T00:00:00.000Z'
 }
];

const ARTICLES=[
 {
  id:'seed-article-digital-strategy-ksa-2026',translation_mode:'bilingual',lang:'ar',status:'published',robots_index:true,robots_follow:true,author:'Mohamed Ali Rassmiy',category:'Strategy',tags:'digital marketing, Saudi Arabia, strategy',published_at:'2026-10-04T09:00:00.000Z',
  title:'استراتيجية التسويق الرقمي في السعودية: خطة عملية للنمو في 2026',title_ar:'استراتيجية التسويق الرقمي في السعودية: خطة عملية للنمو في 2026',title_en:'Digital Marketing Strategy in Saudi Arabia: A Practical 2026 Growth Plan',
  slug:'digital-marketing-strategy-saudi-arabia-2026',slug_ar:'استراتيجية-التسويق-الرقمي-السعودية-2026',slug_en:'digital-marketing-strategy-saudi-arabia-2026',
  short_description_ar:'إطار عملي لبناء استراتيجية تسويق رقمي تربط السوق والجمهور والقنوات والقياس بالـLeads والإيراد.',short_description_en:'A practical framework for building a Saudi digital marketing strategy that connects market, audience, channels and measurement to leads and revenue.',short_description:'إطار عملي لاستراتيجية التسويق الرقمي في السعودية.',
  seo_title_ar:'استراتيجية التسويق الرقمي في السعودية 2026 | خطة عملية',seo_title_en:'Digital Marketing Strategy Saudi Arabia 2026 | Practical Plan',seo_title:'استراتيجية التسويق الرقمي في السعودية 2026',
  meta_description_ar:'تعرف على خطوات بناء استراتيجية تسويق رقمي في السعودية من تحليل السوق إلى SEO والإعلانات والمحتوى والقياس.',meta_description_en:'Build a digital marketing strategy in Saudi Arabia from market diagnosis through SEO, paid media, content and measurement.',meta_description:'استراتيجية تسويق رقمي في السعودية.',
  focus_keyword_ar:'استراتيجية التسويق الرقمي في السعودية',focus_keyword_en:'digital marketing strategy Saudi Arabia',focus_keyword:'استراتيجية التسويق الرقمي في السعودية',
  secondary_keywords_ar:'خطة تسويق رقمي, التسويق الإلكتروني السعودية, استراتيجية نمو',secondary_keywords_en:'Saudi digital marketing plan, marketing strategy KSA, growth strategy',secondary_keywords:'خطة تسويق رقمي',
  content_ar:`<p>الاستراتيجية الجيدة لا تبدأ باختيار منصة إعلانية؛ تبدأ بتحديد أين يأتي النمو وما الذي يمنع العميل من الانتقال من الوعي إلى الشراء.</p><h2>1. ابدأ بهدف تجاري واحد</h2><p>اختر هدفًا يمكن قياسه مثل زيادة فرص البيع المؤهلة أو إيراد المتجر أو خفض تكلفة اكتساب العميل. عندما يكون الهدف واضحًا يصبح تقييم القنوات أسهل.</p><h2>2. ارسم رحلة القرار</h2><p>قسّم الأسئلة التي يطرحها العميل إلى مراحل: اكتشاف المشكلة، مقارنة الحلول، تقييم المورد، ثم قرار الشراء. كل مرحلة تحتاج صفحة أو محتوى أو رسالة مختلفة.</p><h2>3. وزع الأدوار على القنوات</h2><p>SEO لبناء الطلب العضوي، Paid Media لالتقاط وتسريع الطلب، المحتوى لبناء الثقة، وCRM/WhatsApp للمتابعة. لا تجعل كل قناة تعمل كجزيرة منفصلة.</p><h2>4. ابنِ نظام قياس قبل زيادة الميزانية</h2><p>تأكد من تتبع Lead وQualified Lead والبيع والقيمة، وليس الزيارة والنقرة فقط. القناة التي تبدو رخيصة قد تنتج عملاء منخفضي الجودة.</p><h2>5. خطط 90 يومًا</h2><p>قسم العمل إلى Quick Wins، أصول طويلة المدى، وتجارب قابلة للقياس. راجع النتائج أسبوعيًا والاتجاه شهريًا.</p><h2>متى تحتاج مستشارًا خارجيًا؟</h2><p>عندما تكون القنوات كثيرة لكن لا توجد رؤية موحدة، أو عندما ترتفع الميزانية بدون وضوح في العائد، أو عندما تريد خطة تنفيذ تربط الفرق ببعضها.</p><p><a href="/ar/pages/استشاري-تسويق-رقمي-الرياض">اطلع على خدمة الاستشارات التسويقية</a> أو <a href="/ar/contact.html">اطلب جلسة تشخيص</a>.</p>`,
  content_en:`<p>A strong strategy does not start with choosing an ad platform. It starts by identifying where growth can come from and what prevents a buyer from moving from awareness to purchase.</p><h2>1. Start with one commercial objective</h2><p>Choose a measurable goal such as qualified pipeline, store revenue or lower customer acquisition cost. A clear objective makes channel decisions easier.</p><h2>2. Map the decision journey</h2><p>Separate the questions buyers ask into problem discovery, solution comparison, supplier evaluation and purchase. Each stage needs a different page, message or content asset.</p><h2>3. Give channels clear roles</h2><p>SEO builds compounding demand, paid media captures and accelerates demand, content builds trust, while CRM and WhatsApp support follow-up. Avoid channel silos.</p><h2>4. Build measurement before increasing spend</h2><p>Track lead, qualified lead, sale and value—not traffic and clicks alone. Cheap acquisition can still create poor commercial outcomes.</p><h2>5. Plan in 90-day cycles</h2><p>Separate quick wins, long-term assets and measurable experiments. Review execution weekly and direction monthly.</p><h2>When external consulting helps</h2><p>It is useful when many channels exist without a shared strategy, when spend rises without return clarity, or when teams need one execution roadmap.</p><p><a href="/en/pages/digital-marketing-consultant-riyadh">Explore digital marketing consulting</a> or <a href="/en/contact.html">request a diagnosis session</a>.</p>`,
  cta_title_ar:'هل تحتاج خطة 90 يومًا واضحة؟',cta_title_en:'Need a clear 90-day growth plan?',cta_text_ar:'ابدأ بتشخيص القنوات والفرص قبل زيادة الميزانية.',cta_text_en:'Start with a channel and opportunity diagnosis before increasing spend.',cta_button_ar:'اطلب جلسة تشخيص',cta_button_en:'Request a diagnosis',cta_url_ar:'/ar/contact.html',cta_url_en:'/en/contact.html',
  og_title_ar:'استراتيجية التسويق الرقمي في السعودية 2026',og_title_en:'Digital Marketing Strategy Saudi Arabia 2026',og_description_ar:'خطة عملية تربط القنوات بالـLeads والإيراد.',og_description_en:'A practical plan tying channels to leads and revenue.',og_image_ar:'',og_image_en:'',schema_type:'Article',schema_type_ar:'Article',schema_type_en:'Article',schema_json:'',schema_json_ar:'',schema_json_en:'',created_at:'2026-10-04T09:00:00.000Z',updated_at:'2026-10-04T09:00:00.000Z'
 },
 {
  id:'seed-article-seo-vs-google-ads',translation_mode:'bilingual',lang:'ar',status:'published',robots_index:true,robots_follow:true,author:'Mohamed Ali Rassmiy',category:'SEO & Paid Media',tags:'SEO, Google Ads, Saudi Arabia',published_at:'2026-10-04T09:10:00.000Z',
  title:'SEO أم Google Ads في السعودية؟ كيف تختار القناة المناسبة',title_ar:'SEO أم Google Ads في السعودية؟ كيف تختار القناة المناسبة',title_en:'SEO vs Google Ads in Saudi Arabia: How to Choose the Right Channel',
  slug:'seo-vs-google-ads-saudi-arabia',slug_ar:'seo-ام-google-ads-السعودية',slug_en:'seo-vs-google-ads-saudi-arabia',
  short_description_ar:'مقارنة عملية بين SEO وGoogle Ads حسب السرعة والتكلفة ونية البحث ونمو الـPipeline.',short_description_en:'A practical SEO vs Google Ads comparison based on speed, cost, search intent and pipeline growth.',short_description:'SEO أم Google Ads في السعودية؟',
  seo_title_ar:'SEO أم Google Ads في السعودية؟ مقارنة عملية',seo_title_en:'SEO vs Google Ads Saudi Arabia | Practical Comparison',seo_title:'SEO أم Google Ads في السعودية',
  meta_description_ar:'متى تستخدم SEO ومتى تستخدم Google Ads؟ مقارنة تساعد الشركات في السعودية على اختيار المزيج المناسب للنمو.',meta_description_en:'When should Saudi businesses use SEO or Google Ads? Compare speed, intent, cost and compounding value.',meta_description:'مقارنة SEO وGoogle Ads.',
  focus_keyword_ar:'SEO أم Google Ads',focus_keyword_en:'SEO vs Google Ads Saudi Arabia',focus_keyword:'SEO أم Google Ads',
  secondary_keywords_ar:'تحسين محركات البحث السعودية, إعلانات جوجل السعودية',secondary_keywords_en:'SEO Saudi Arabia, Google Ads Saudi Arabia',secondary_keywords:'SEO السعودية, Google Ads السعودية',
  content_ar:`<p>السؤال الصحيح ليس: أيهما أفضل؟ بل: ما الدور الذي يجب أن تلعبه كل قناة في رحلة العميل ونمو الشركة؟</p><h2>متى يكون Google Ads مناسبًا؟</h2><p>عندما تحتاج طلبًا سريعًا، وتوجد كلمات تجارية واضحة، ويمكنك قياس التحويل والقيمة. الإعلانات ممتازة لاختبار الرسائل والصفحات بسرعة.</p><h2>متى يكون SEO أقوى؟</h2><p>عندما يوجد حجم بحث مستمر، وتريد خفض الاعتماد على الدفع مقابل كل زيارة، ولديك القدرة على بناء صفحات ومحتوى وروابط داخلية بشكل منظم.</p><h2>أين يحدث الخطأ؟</h2><p>الاعتماد الكامل على الإعلانات يجعل تكلفة النمو مرتبطة بالميزانية، بينما SEO بدون صفحات تحويل وقياس قد يجلب زيارات بلا قيمة تجارية.</p><h2>المزيج الأفضل</h2><p>استخدم Ads لالتقاط الطلب الآن واختبار الكلمات والرسائل، ثم استخدم نتائج البحث المدفوع لتحديد فرص SEO طويلة المدى. شارك بيانات التحويل بين القناتين.</p><h2>قاعدة قرار بسيطة</h2><ul><li>تحتاج Leads هذا الشهر؟ ابدأ Paid Search مع Landing Page قوية.</li><li>لديك كلمات مهمة وتكلفتها مرتفعة باستمرار؟ ابنِ SEO حولها.</li><li>لا تعرف أي الكلمات تتحول؟ استخدم Ads كاختبار سريع قبل توسيع المحتوى.</li></ul><p><a href="/ar/contact.html?service=paid-media">اطلب مراجعة المزيج بين SEO والإعلانات</a>.</p>`,
  content_en:`<p>The useful question is not “which is better?” It is “what role should each channel play in the buyer journey and growth model?”</p><h2>When Google Ads fits</h2><p>Use it when you need demand quickly, commercial search terms are clear and conversion value can be measured. Paid search is also useful for testing messages and landing pages fast.</p><h2>When SEO becomes stronger</h2><p>SEO is powerful when search demand is persistent, you want less dependency on paying for every visit and you can build structured pages, content and internal linking.</p><h2>The common mistake</h2><p>Paid-only growth makes acquisition cost tightly linked to budget, while SEO without conversion pages and measurement can generate traffic without commercial value.</p><h2>The better mix</h2><p>Use Ads to capture demand now and test keywords/messages, then use paid-search data to prioritise long-term SEO opportunities. Share conversion intelligence across both channels.</p><h2>A simple decision rule</h2><ul><li>Need leads this month? Start with paid search and a strong landing page.</li><li>Paying heavily for important terms every month? Build SEO around them.</li><li>Unsure which terms convert? Use Ads as a fast validation layer.</li></ul><p><a href="/en/contact.html?service=paid-media">Request an SEO + paid search review</a>.</p>`,
  cta_title_ar:'لا تختار القناة بمعزل عن البيانات',cta_title_en:'Do not choose a channel without data',cta_text_ar:'راجع تكلفة الاستحواذ وجودة الـLead قبل توزيع الميزانية.',cta_text_en:'Review acquisition cost and lead quality before reallocating budget.',cta_button_ar:'اطلب مراجعة',cta_button_en:'Request a review',cta_url_ar:'/ar/contact.html',cta_url_en:'/en/contact.html',
  og_title_ar:'SEO أم Google Ads في السعودية؟',og_title_en:'SEO vs Google Ads in Saudi Arabia',og_description_ar:'مقارنة عملية لاتخاذ قرار تسويقي أفضل.',og_description_en:'A practical comparison for better channel decisions.',og_image_ar:'',og_image_en:'',schema_type:'Article',schema_type_ar:'Article',schema_type_en:'Article',schema_json:'',schema_json_ar:'',schema_json_en:'',created_at:'2026-10-04T09:10:00.000Z',updated_at:'2026-10-04T09:10:00.000Z'
 },
 {
  id:'seed-article-seo-consultant-guide',translation_mode:'bilingual',lang:'ar',status:'published',robots_index:true,robots_follow:true,author:'Mohamed Ali Rassmiy',category:'SEO',tags:'SEO consultant, Riyadh, Saudi Arabia',published_at:'2026-10-04T09:20:00.000Z',
  title:'كيف تختار مستشار SEO في الرياض؟ 10 أسئلة قبل التعاقد',title_ar:'كيف تختار مستشار SEO في الرياض؟ 10 أسئلة قبل التعاقد',title_en:'How to Choose an SEO Consultant in Riyadh: 10 Questions Before You Hire',
  slug:'choose-seo-consultant-riyadh',slug_ar:'كيف-تختار-مستشار-seo-الرياض',slug_en:'choose-seo-consultant-riyadh',
  short_description_ar:'أسئلة تساعدك على تقييم خبرة مستشار SEO وطريقة القياس والتنفيذ قبل التعاقد.',short_description_en:'Questions to evaluate an SEO consultant’s strategy, execution and measurement before hiring.',short_description:'كيف تختار مستشار SEO في الرياض؟',
  seo_title_ar:'كيف تختار مستشار SEO في الرياض؟ 10 أسئلة مهمة',seo_title_en:'How to Choose an SEO Consultant in Riyadh | 10 Questions',seo_title:'اختيار مستشار SEO في الرياض',
  meta_description_ar:'دليل عملي لاختيار مستشار SEO في الرياض: التقنية، المحتوى، القياس، التقارير، نية البحث وربط SEO بالـLeads.',meta_description_en:'A practical guide to choosing an SEO consultant in Riyadh across technical SEO, content, measurement and lead impact.',meta_description:'دليل اختيار مستشار SEO.',
  focus_keyword_ar:'مستشار SEO في الرياض',focus_keyword_en:'SEO consultant Riyadh',focus_keyword:'مستشار SEO في الرياض',
  secondary_keywords_ar:'شركة SEO الرياض, خبير SEO السعودية',secondary_keywords_en:'SEO expert Riyadh, SEO agency Saudi Arabia',secondary_keywords:'شركة SEO الرياض',
  content_ar:`<p>الاختيار الصحيح لا يعتمد على وعود الوصول للمرتبة الأولى. ركز على طريقة التفكير والقياس والتنفيذ.</p><h2>الأسئلة العشرة</h2><ol><li>كيف تربط الكلمات بنية الشراء؟</li><li>كيف تحدد الأولويات التقنية؟</li><li>كيف تقرر إنشاء صفحة جديدة أو تحسين صفحة موجودة؟</li><li>ما الذي ستقيسه بجانب الزيارات والترتيب؟</li><li>كيف تربط Search Console وAnalytics بالـLeads؟</li><li>كيف ستستخدم المحتوى لدعم الصفحات التجارية؟</li><li>كيف تتعامل مع Cannibalization؟</li><li>ما خطة الروابط الداخلية؟</li><li>كيف تتعامل مع AEO وAI search؟</li><li>كيف يبدو أول 90 يومًا؟</li></ol><h2>إشارات تحذير</h2><p>ضمان المرتبة الأولى، شراء روابط بكميات، تقارير مليئة بالأرقام بدون قرارات، أو إنشاء عشرات الصفحات بدون منطق واضح.</p><h2>الإشارة الإيجابية</h2><p>المستشار الجيد يستطيع شرح لماذا هذه الصفحة، لهذه الكلمة، في هذه المرحلة، وكيف ستساهم في Lead أو بيع.</p><p><a href="/ar/pages/استشاري-seo-الرياض">راجع منهجية استشارات SEO</a>.</p>`,
  content_en:`<p>The right choice is not based on promises of “#1 rankings.” Evaluate how the consultant thinks, prioritises, executes and measures.</p><h2>Ten questions to ask</h2><ol><li>How do you map keywords to buying intent?</li><li>How do you prioritise technical SEO?</li><li>When do you create a new page vs improve an existing one?</li><li>What do you measure beyond traffic and rankings?</li><li>How do you connect Search Console and Analytics to leads?</li><li>How does content support commercial pages?</li><li>How do you handle cannibalisation?</li><li>What is your internal-linking plan?</li><li>How do you approach AEO and AI search?</li><li>What should the first 90 days look like?</li></ol><h2>Red flags</h2><p>Guaranteed #1 positions, bulk link buying, reports with numbers but no decisions, or mass page creation without a clear intent model.</p><h2>The positive signal</h2><p>A strong consultant can explain why a page should exist, which intent it serves and how it can contribute to a lead or sale.</p><p><a href="/en/pages/seo-consultant-riyadh">Review my SEO consulting approach</a>.</p>`,
  cta_title_ar:'قيّم SEO قبل التعاقد',cta_title_en:'Evaluate SEO before you hire',cta_text_ar:'اطلب مراجعة أولية للموقع وخريطة الفرص.',cta_text_en:'Request an initial site and opportunity review.',cta_button_ar:'اطلب المراجعة',cta_button_en:'Request review',cta_url_ar:'/ar/contact.html?service=seo-aeo',cta_url_en:'/en/contact.html?service=seo-aeo',
  og_title_ar:'كيف تختار مستشار SEO في الرياض؟',og_title_en:'How to Choose an SEO Consultant in Riyadh',og_description_ar:'10 أسئلة عملية قبل التعاقد.',og_description_en:'10 practical questions before hiring.',og_image_ar:'',og_image_en:'',schema_type:'Article',schema_type_ar:'Article',schema_type_en:'Article',schema_json:'',schema_json_ar:'',schema_json_en:'',created_at:'2026-10-04T09:20:00.000Z',updated_at:'2026-10-04T09:20:00.000Z'
 },
 {
  id:'seed-article-aeo-geo',translation_mode:'bilingual',lang:'ar',status:'published',robots_index:true,robots_follow:true,author:'Mohamed Ali Rassmiy',category:'AEO & GEO',tags:'AEO, GEO, AI search, SEO',published_at:'2026-10-04T09:30:00.000Z',
  title:'AEO وGEO: كيف تجعل علامتك قابلة للظهور في إجابات الذكاء الاصطناعي',title_ar:'AEO وGEO: كيف تجعل علامتك قابلة للظهور في إجابات الذكاء الاصطناعي',title_en:'AEO & GEO: How to Make Your Brand Discoverable in AI Answers',
  slug:'aeo-geo-ai-search-saudi-arabia',slug_ar:'aeo-geo-الظهور-في-اجابات-الذكاء-الاصطناعي',slug_en:'aeo-geo-ai-search-saudi-arabia',
  short_description_ar:'خطوات عملية لبناء محتوى واضح وموثوق ومهيأ لمحركات الإجابة والبحث المدعوم بالذكاء الاصطناعي.',short_description_en:'Practical steps for creating clear, trustworthy content that is easier for answer engines and AI search systems to understand.',short_description:'AEO وGEO للظهور في نتائج الذكاء الاصطناعي.',
  seo_title_ar:'AEO وGEO للظهور في إجابات الذكاء الاصطناعي',seo_title_en:'AEO & GEO for AI Search Visibility | Practical Guide',seo_title:'AEO وGEO',
  meta_description_ar:'تعرف على AEO وGEO وكيف تبني صفحات ومحتوى منظمًا وواضحًا يساعد محركات الإجابة والذكاء الاصطناعي على فهم علامتك.',meta_description_en:'Learn AEO and GEO techniques that help answer engines and AI search understand, retrieve and cite your brand content.',meta_description:'AEO وGEO.',
  focus_keyword_ar:'AEO وGEO',focus_keyword_en:'AEO GEO AI search',focus_keyword:'AEO وGEO',
  secondary_keywords_ar:'تحسين محركات الإجابة, الظهور في الذكاء الاصطناعي, AI SEO',secondary_keywords_en:'answer engine optimization, generative engine optimization, AI SEO',secondary_keywords:'تحسين محركات الإجابة',
  content_ar:`<p>البحث لم يعد قائمة روابط فقط. المستخدم قد يحصل على إجابة مركبة قبل زيارة أي موقع، ولذلك يجب أن يكون المحتوى سهل الفهم والاستخراج والتحقق.</p><h2>ابدأ بالوضوح</h2><p>عرّف الكيان والخدمة والموقع والجمهور بوضوح. تجنب مقدمات طويلة قبل الوصول للإجابة الأساسية.</p><h2>اكتب بصيغة سؤال وجواب</h2><p>ضع إجابات مباشرة للأسئلة التجارية والمعلوماتية، ثم وسّع الشرح بالأمثلة والخطوات.</p><h2>ابنِ أدلة ثقة</h2><p>صفحات About واضحة، خبرة قابلة للتحقق، دراسات حالة، معلومات اتصال ثابتة، ومصادر عند تقديم أرقام أو ادعاءات.</p><h2>اربط الكيانات داخليًا</h2><p>اربط المقالات بصفحات الخدمات، والخدمات بدراسات الحالة، والأسئلة بصفحات أعمق. هذا يساعد المستخدم ومحركات البحث على فهم العلاقة بين الموضوعات.</p><h2>لا تنس SEO التقليدي</h2><p>AEO وGEO لا يلغيان الأساسيات: قابلية الزحف، Canonical، سرعة الصفحة، بنية العناوين، الروابط الداخلية وبيانات منظمة صحيحة.</p><p><a href="/ar/pages/استشاري-seo-الرياض">اطلب خريطة SEO + AEO للموقع</a>.</p>`,
  content_en:`<p>Search is no longer only a list of links. Users can receive synthesized answers before visiting a website, so content must be easy to understand, retrieve and verify.</p><h2>Start with clarity</h2><p>Clearly define the entity, service, location and audience. Avoid long introductions before the direct answer.</p><h2>Use question-first structures</h2><p>Answer commercial and informational questions directly, then expand with context, examples and steps.</p><h2>Build trust signals</h2><p>Use clear About pages, verifiable expertise, case studies, consistent contact information and sources when presenting external facts or numbers.</p><h2>Connect entities internally</h2><p>Link articles to services, services to case studies and summaries to deeper resources. This improves both user navigation and semantic understanding.</p><h2>Do not skip traditional SEO</h2><p>AEO and GEO do not replace crawlability, canonicals, performance, heading structure, internal links or valid structured data.</p><p><a href="/en/pages/seo-consultant-riyadh">Request an SEO + AEO roadmap</a>.</p>`,
  cta_title_ar:'هل محتواك مفهوم لمحركات الإجابة؟',cta_title_en:'Can answer engines understand your content?',cta_text_ar:'ابدأ بمراجعة البنية والكيانات والأسئلة التي يجب أن يجيب عنها موقعك.',cta_text_en:'Start by reviewing structure, entities and the questions your site should answer.',cta_button_ar:'راجع موقعي',cta_button_en:'Review my site',cta_url_ar:'/ar/contact.html?service=seo-aeo',cta_url_en:'/en/contact.html?service=seo-aeo',
  og_title_ar:'AEO وGEO للظهور في الذكاء الاصطناعي',og_title_en:'AEO & GEO for AI Search Visibility',og_description_ar:'إطار عملي لتحسين قابلية فهم واسترجاع المحتوى.',og_description_en:'A practical framework for AI-search discoverability.',og_image_ar:'',og_image_en:'',schema_type:'Article',schema_type_ar:'Article',schema_type_en:'Article',schema_json:'',schema_json_ar:'',schema_json_en:'',created_at:'2026-10-04T09:30:00.000Z',updated_at:'2026-10-04T09:30:00.000Z'
 },
 {
  id:'seed-article-ecommerce-growth',translation_mode:'bilingual',lang:'ar',status:'published',robots_index:true,robots_follow:true,author:'Mohamed Ali Rassmiy',category:'E-Commerce',tags:'ecommerce, CRO, Saudi Arabia',published_at:'2026-10-04T09:40:00.000Z',
  title:'استراتيجية نمو المتاجر الإلكترونية في السعودية: أين تبحث عن الإيراد أولًا؟',title_ar:'استراتيجية نمو المتاجر الإلكترونية في السعودية: أين تبحث عن الإيراد أولًا؟',title_en:'E-Commerce Growth in Saudi Arabia: Where to Look for Revenue First',
  slug:'ecommerce-growth-strategy-saudi-arabia',slug_ar:'استراتيجية-نمو-المتاجر-الإلكترونية-السعودية',slug_en:'ecommerce-growth-strategy-saudi-arabia',
  short_description_ar:'إطار لتحديد أكبر فرص نمو المتجر بين Acquisition وCRO وSEO وFeeds والاحتفاظ بالعملاء.',short_description_en:'A framework to identify the biggest e-commerce growth opportunities across acquisition, CRO, SEO, feeds and retention.',short_description:'استراتيجية نمو المتاجر الإلكترونية في السعودية.',
  seo_title_ar:'استراتيجية نمو المتاجر الإلكترونية في السعودية',seo_title_en:'E-Commerce Growth Strategy Saudi Arabia | Revenue Priorities',seo_title:'استراتيجية نمو المتاجر الإلكترونية',
  meta_description_ar:'كيف تحدد أولويات نمو متجر إلكتروني في السعودية بين الزيارات وCRO وSEO وMerchant Center وTracking والاحتفاظ؟',meta_description_en:'How to prioritise e-commerce growth in Saudi Arabia across traffic, CRO, SEO, Merchant Center, tracking and retention.',meta_description:'نمو المتاجر الإلكترونية.',
  focus_keyword_ar:'استراتيجية نمو المتاجر الإلكترونية',focus_keyword_en:'ecommerce growth strategy Saudi Arabia',focus_keyword:'استراتيجية نمو المتاجر الإلكترونية',
  secondary_keywords_ar:'تسويق متجر إلكتروني, CRO, Merchant Center',secondary_keywords_en:'ecommerce marketing Saudi Arabia, CRO, Merchant Center',secondary_keywords:'تسويق متجر إلكتروني',
  content_ar:`<p>أسرع طريق للنمو ليس دائمًا زيادة الميزانية الإعلانية. أحيانًا يكون أكبر أثر في صفحة المنتج أو سرعة الدفع أو جودة الـFeed.</p><h2>ابدأ بمعادلة الإيراد</h2><p>الإيراد = زيارات × معدل تحويل × متوسط قيمة الطلب. أضف معدل التكرار إذا كان الشراء متكررًا. هذه المعادلة تكشف أين يوجد أكبر رافعة.</p><h2>افحص جودة الزيارات</h2><p>قسّم الأداء حسب المصدر والجهاز والفئة والمنتج. لا تخلط زيارات الوعي مع زيارات نية الشراء عند تقييم التحويل.</p><h2>راجع صفحات المنتج</h2><p>العنوان، الصور، المواصفات، الشحن، الثقة، الأسئلة الشائعة والمراجعات تؤثر مباشرة على القرار.</p><h2>تأكد من القياس والـFeeds</h2><p>Tracking غير مكتمل يضلل قرارات الميزانية. وFeed ضعيف يضعف Shopping حتى لو الحملة نفسها جيدة.</p><h2>ابنِ SEO للفئات والمنتجات</h2><p>الفئات تستهدف الطلب المتكرر، والمنتجات تستهدف استعلامات دقيقة، والمحتوى يلتقط الأسئلة التي تسبق الشراء.</p><p><a href="/ar/pages/نمو-المتاجر-الإلكترونية-السعودية">اطلع على خدمة نمو المتاجر</a>.</p>`,
  content_en:`<p>The fastest path to growth is not always more ad spend. The largest opportunity may sit in product pages, checkout friction or feed quality.</p><h2>Start with the revenue equation</h2><p>Revenue = traffic × conversion rate × average order value. Add repeat rate when the model supports repeat purchase. This quickly shows which lever matters most.</p><h2>Review traffic quality</h2><p>Segment performance by source, device, category and product. Do not mix awareness traffic with high-intent traffic when evaluating conversion.</p><h2>Audit product pages</h2><p>Titles, imagery, specifications, shipping, trust, FAQs and reviews all influence the decision.</p><h2>Validate tracking and feeds</h2><p>Incomplete tracking leads to poor budget decisions. Weak feeds limit Shopping performance even when campaign setup is strong.</p><h2>Build SEO for categories and products</h2><p>Categories capture recurring demand, products capture precise queries and content answers questions that appear before purchase.</p><p><a href="/en/pages/ecommerce-growth-saudi-arabia">Explore e-commerce growth consulting</a>.</p>`,
  cta_title_ar:'اكتشف أكبر تسرب في إيراد متجرك',cta_title_en:'Find the biggest revenue leak in your store',cta_text_ar:'ابدأ بمراجعة التحويل والقياس والقنوات قبل زيادة الإنفاق.',cta_text_en:'Review conversion, measurement and channels before increasing spend.',cta_button_ar:'اطلب مراجعة المتجر',cta_button_en:'Request store review',cta_url_ar:'/ar/contact.html?service=ecommerce-growth',cta_url_en:'/en/contact.html?service=ecommerce-growth',
  og_title_ar:'استراتيجية نمو المتاجر الإلكترونية في السعودية',og_title_en:'E-Commerce Growth Strategy in Saudi Arabia',og_description_ar:'حدد أولويات الإيراد قبل زيادة الميزانية.',og_description_en:'Prioritise revenue levers before adding spend.',og_image_ar:'',og_image_en:'',schema_type:'Article',schema_type_ar:'Article',schema_type_en:'Article',schema_json:'',schema_json_ar:'',schema_json_en:'',created_at:'2026-10-04T09:40:00.000Z',updated_at:'2026-10-04T09:40:00.000Z'
 },
 {
  id:'seed-article-b2b-leads',translation_mode:'bilingual',lang:'ar',status:'published',robots_index:true,robots_follow:true,author:'Mohamed Ali Rassmiy',category:'Lead Generation',tags:'B2B, leads, Saudi Arabia',published_at:'2026-10-04T09:50:00.000Z',
  title:'B2B Lead Generation في السعودية: نظام عملي بدل جمع Leads عشوائية',title_ar:'B2B Lead Generation في السعودية: نظام عملي بدل جمع Leads عشوائية',title_en:'B2B Lead Generation in Saudi Arabia: Build a System, Not a List of Random Leads',
  slug:'b2b-lead-generation-saudi-arabia',slug_ar:'b2b-lead-generation-السعودية',slug_en:'b2b-lead-generation-saudi-arabia',
  short_description_ar:'كيف تبني نظام B2B يربط ICP والمحتوى والبحث والإعلانات وصفحات التحويل والمتابعة بجودة الفرصة.',short_description_en:'How to connect ICP, content, search, paid media, landing pages and follow-up into a B2B lead system.',short_description:'B2B Lead Generation في السعودية.',
  seo_title_ar:'B2B Lead Generation في السعودية | نظام عملي',seo_title_en:'B2B Lead Generation Saudi Arabia | Practical System',seo_title:'B2B Lead Generation السعودية',
  meta_description_ar:'دليل لبناء نظام B2B Lead Generation في السعودية يركز على ICP والنية والصفحات والتحويل والمتابعة وجودة الفرصة.',meta_description_en:'A practical B2B lead generation system for Saudi Arabia built around ICP, intent, conversion and lead quality.',meta_description:'B2B Lead Generation في السعودية.',
  focus_keyword_ar:'B2B Lead Generation في السعودية',focus_keyword_en:'B2B lead generation Saudi Arabia',focus_keyword:'B2B Lead Generation في السعودية',
  secondary_keywords_ar:'توليد العملاء المحتملين B2B, تسويق B2B السعودية',secondary_keywords_en:'B2B marketing Saudi Arabia, qualified leads Saudi Arabia',secondary_keywords:'تسويق B2B السعودية',
  content_ar:`<p>عدد الـLeads وحده لا يقول الكثير. النظام الجيد ينتج فرصًا يعرف فريق المبيعات ماذا يفعل بها.</p><h2>حدد ICP أولًا</h2><p>القطاع، حجم الشركة، الدور الوظيفي، المشكلة، التوقيت، وقيمة الفرصة. كلما كان التعريف أوضح أصبح المحتوى والإعلان أكثر دقة.</p><h2>ابنِ صفحات حسب المشكلة</h2><p>صفحة عامة واحدة لا تكفي دائمًا. أنشئ صفحات للحالات المهمة بحيث يرى الزائر مشكلته ولغته ودليله الاجتماعي.</p><h2>استخدم المحتوى لتقليل المخاطرة</h2><p>مقالات المقارنة، Checklists، دراسات الحالة وإجابات الاعتراضات تساعد العميل قبل التحدث مع المبيعات.</p><h2>التقط النية عبر Search</h2><p>ادمج SEO وPaid Search حول الكلمات التي تعبّر عن بحث عن حل أو مورد، وليس فقط الكلمات ذات الحجم الأعلى.</p><h2>عرّف Lead Quality</h2><p>اتفق مع المبيعات على MQL وSQL أو معيار بسيط واضح. ثم ارجع بيانات الجودة إلى الحملات والمحتوى.</p><h2>تابع بسرعة وبسياق</h2><p>الـLead الذي طلب خدمة معينة يجب أن يتلقى متابعة مرتبطة بطلبه، لا رسالة عامة.</p><p><a href="/ar/contact.html">ناقش نظام Lead Generation لشركتك</a>.</p>`,
  content_en:`<p>Lead volume alone says very little. A strong B2B system creates opportunities that sales knows how to progress.</p><h2>Define the ICP first</h2><p>Industry, company size, role, problem, timing and opportunity value. The clearer the ICP, the more precise the content and acquisition strategy.</p><h2>Build problem-specific pages</h2><p>One generic page is not always enough. Create pages for high-value use cases so visitors see their problem, language and relevant proof.</p><h2>Use content to reduce risk</h2><p>Comparison articles, checklists, case studies and objection-handling content help buyers before they speak with sales.</p><h2>Capture intent through search</h2><p>Combine SEO and paid search around solution and supplier intent—not only the highest-volume terms.</p><h2>Define lead quality</h2><p>Agree with sales on MQL/SQL or a simpler qualification definition, then send quality feedback back into campaigns and content.</p><h2>Follow up quickly and with context</h2><p>A lead asking about a specific service should receive follow-up that reflects that request, not a generic response.</p><p><a href="/en/contact.html">Discuss a B2B lead generation system</a>.</p>`,
  cta_title_ar:'هل تحتاج Leads أقل لكن أفضل؟',cta_title_en:'Need fewer leads—but better ones?',cta_text_ar:'ابدأ بتعريف ICP وجودة الـLead ومسار التحويل.',cta_text_en:'Start with ICP, lead quality and the conversion path.',cta_button_ar:'ناقش النظام',cta_button_en:'Discuss the system',cta_url_ar:'/ar/contact.html',cta_url_en:'/en/contact.html',
  og_title_ar:'B2B Lead Generation في السعودية',og_title_en:'B2B Lead Generation in Saudi Arabia',og_description_ar:'نظام يركز على جودة الفرصة لا عدد النماذج.',og_description_en:'A system focused on opportunity quality, not form volume.',og_image_ar:'',og_image_en:'',schema_type:'Article',schema_type_ar:'Article',schema_type_en:'Article',schema_json:'',schema_json_ar:'',schema_json_en:'',created_at:'2026-10-04T09:50:00.000Z',updated_at:'2026-10-04T09:50:00.000Z'
 }
];

const cardsJson=JSON.stringify(CARDS);
const pagesJson=JSON.stringify(PAGES);
const articlesJson=JSON.stringify(ARTICLES);

if(!app.includes('const RASSMIY_DEFAULT_CARDS_V60=')){
  app=app.replace('function adminContent(state,session,url){',
`const RASSMIY_DEFAULT_CARDS_V60=${cardsJson};
const RASSMIY_SEED_PAGES_V60=${pagesJson};
const RASSMIY_SEED_ARTICLES_V60=${articlesJson};
function rassmiyCards(state){ try{ const raw=String(state.settings?.cards_json||'').trim(); if(!raw)return RASSMIY_DEFAULT_CARDS_V60; const x=JSON.parse(raw); return Array.isArray(x)?x:RASSMIY_DEFAULT_CARDS_V60; }catch{return RASSMIY_DEFAULT_CARDS_V60;} }
function adminContent(state,session,url){`);
}

if(!app.includes("action==='save_cards'")){
  const start=app.indexOf("    if(action==='save_site_settings')");
  if(start<0) throw new Error('save_site_settings anchor missing');
  const next=app.indexOf("    if(action===",start+20);
  const insert=`    if(action==='save_cards'){ requirePermission(state,session,'settings'); let cards=[]; try{cards=JSON.parse(String(f.cards_json||'[]'));}catch{throw new Error('Invalid cards JSON');} if(!Array.isArray(cards)||cards.length>80)throw new Error('Invalid cards payload'); cards=cards.map((x,i)=>({id:String(x.id||('card-'+i)).slice(0,80),collection:['service','portfolio','proof','testimonial'].includes(x.collection)?x.collection:'service',order:Number(x.order||i*10),enabled:x.enabled!==false,icon:String(x.icon||'').slice(0,20),image:String(x.image||'').slice(0,500),title_ar:String(x.title_ar||'').slice(0,180),title_en:String(x.title_en||'').slice(0,180),description_ar:String(x.description_ar||'').slice(0,1000),description_en:String(x.description_en||'').slice(0,1000),eyebrow_ar:String(x.eyebrow_ar||'').slice(0,120),eyebrow_en:String(x.eyebrow_en||'').slice(0,120),metric_ar:String(x.metric_ar||'').slice(0,120),metric_en:String(x.metric_en||'').slice(0,120),cta_label_ar:String(x.cta_label_ar||'').slice(0,120),cta_label_en:String(x.cta_label_en||'').slice(0,120),cta_url_ar:String(x.cta_url_ar||'').slice(0,500),cta_url_en:String(x.cta_url_en||'').slice(0,500),alt_ar:String(x.alt_ar||'').slice(0,180),alt_en:String(x.alt_en||'').slice(0,180)})); state.settings.cards_json=JSON.stringify(cards); logActivity(state,session,'Updated','settings','Editable cards'); await saveState(state); return redirect(flashUrl('/admin?section=settings&cards=1#card-manager','تم حفظ الكروت.')); }
`;
  app=app.slice(0,next)+insert+app.slice(next);
}
if(!app.includes("save_cards:'settings'")){
  app=app.replace("save_site_settings:'settings',","save_site_settings:'settings',save_cards:'settings',");
}

if(!app.includes("path==='/api/cards'")){
  const anchor="  if(path==='/api/health')";
  if(!app.includes(anchor)) throw new Error('api health anchor missing');
  app=app.replace(anchor,`  if(path==='/api/cards' && req.method==='GET'){ try{ const payload={cards:[...rassmiyCards(state)].sort((a,b)=>Number(a.order||0)-Number(b.order||0))}; return text(JSON.stringify(payload),200,'application/json; charset=utf-8',{'Cache-Control':'no-store'}); }catch(e){ return text(JSON.stringify({cards:RASSMIY_DEFAULT_CARDS_V60,error:'fallback'}),200,'application/json; charset=utf-8',{'Cache-Control':'no-store'}); } }
`+anchor);
}


if(app.includes("const add=(loc,lastmod='',priority='0.7',changefreq='monthly',alts=[])=>items.push({loc,lastmod,priority,changefreq,alts}); const homeAlts=")){
 app=app.replace("const add=(loc,lastmod='',priority='0.7',changefreq='monthly',alts=[])=>items.push({loc,lastmod,priority,changefreq,alts}); const homeAlts=",
 "const add=(loc,lastmod='',priority='0.7',changefreq='monthly',alts=[])=>items.push({loc,lastmod,priority,changefreq,alts}); const growthStatic=[...RASSMIY_SEED_PAGES_V60.flatMap(p=>['ar','en'].map(lang=>({lang,href:base+'/'+lang+'/pages/'+encodeURIComponent(lang==='ar'?p.slug_ar:p.slug_en)}))),...['ar','en'].map(lang=>({lang,href:base+'/'+lang+'/articles'})),...RASSMIY_SEED_ARTICLES_V60.flatMap(a=>['ar','en'].map(lang=>({lang,href:base+'/'+lang+'/articles/'+encodeURIComponent(lang==='ar'?a.slug_ar:a.slug_en)})))]; for(const x of growthStatic)add(x.href,'','0.8','weekly',[]); const homeAlts=");
}
// GROWTH_SITEMAP_V61

fs.writeFileSync(appFile,app);

const cardKeysService=['service-seo','service-paid','service-social','service-ecommerce','service-content','service-events','service-analytics'];
const cardKeysPortfolio=['case-ecommerce','case-seo','case-paid','case-events','case-brand','case-education'];
function annotate(file,cls,keys){
  if(!fs.existsSync(file))return;
  let h=fs.readFileSync(file,'utf8'),i=0;
  const re=new RegExp('<article class="'+cls+'"','g');
  h=h.replace(re,m=>{const key=keys[i++];return key?'<article class="'+cls+'" data-card-key="'+key+'"':m;});
  fs.writeFileSync(file,h);
}
for(const lang of ['ar','en']){
  annotate(path.join(root,lang,'index.html'),'service-card',cardKeysService);
  annotate(path.join(root,lang,'services.html'),'service-card',cardKeysService);
  annotate(path.join(root,lang,'portfolio.html'),'case-card',cardKeysPortfolio);
}
annotate(path.join(root,'index.html'),'service-card',cardKeysService);

const cssFile=path.join(root,'assets','styles.css');
let css=fs.readFileSync(cssFile,'utf8');
if(!css.includes('Rassmiy growth system v6.0')){
 css+=`
/* Rassmiy growth system v6.0 */
.growth-section{padding:72px 0}.growth-section.soft{background:#f5f8fb}.growth-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.growth-card{padding:24px;border:1px solid #dfe8f0;border-radius:20px;background:#fff}.growth-card h3{margin:8px 0 10px;color:#0d3157}.growth-card p{color:#60758c;line-height:1.8}.growth-kicker{font-weight:900;color:#ff7418;text-transform:uppercase;letter-spacing:.06em}.growth-copy{max-width:760px}.growth-steps{counter-reset:step;display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.growth-step{padding:20px;border-radius:18px;background:#0b3158;color:#fff}.growth-step:before{counter-increment:step;content:counter(step);display:inline-grid;place-items:center;width:34px;height:34px;border-radius:50%;background:#ff7418;font-weight:900;margin-bottom:16px}.growth-faq details{border-top:1px solid #dfe8f0;padding:16px 0}.growth-faq summary{font-weight:900;cursor:pointer;color:#0d3157}.growth-cta{display:flex;gap:12px;flex-wrap:wrap;margin-top:22px}.editable-card-media{width:100%;aspect-ratio:16/9;object-fit:cover;border-radius:14px;margin-bottom:14px}.card-eyebrow{font-size:12px;font-weight:900;text-transform:uppercase;letter-spacing:.06em;color:#ff7418}.card-metric{font-weight:900;color:#0b5e92;margin-top:10px}.card-manager{margin-top:22px}.card-manager-toolbar{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:14px}.card-editor-list{display:grid;gap:14px}.card-editor-item{border:1px solid #dbe5ee;border-radius:16px;background:#fff;padding:14px}.card-editor-item summary{cursor:pointer;font-weight:900}.card-editor-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin-top:14px}.card-editor-grid label{display:grid;gap:6px}.card-editor-grid input,.card-editor-grid textarea,.card-editor-grid select{width:100%;box-sizing:border-box;padding:10px;border:1px solid #ccd9e5;border-radius:10px}.card-editor-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.card-editor-actions button{padding:8px 11px;border:1px solid #ccd9e5;border-radius:9px;background:#fff;cursor:pointer}.card-editor-actions .danger{color:#b42318;border-color:#f3b7b2}.card-manager-status{margin-top:10px;font-weight:800}.service-card[hidden],.case-card[hidden]{display:none!important}
@media(max-width:900px){.growth-grid{grid-template-columns:1fr 1fr}.growth-steps{grid-template-columns:1fr 1fr}}
@media(max-width:620px){.growth-section{padding:52px 0}.growth-grid,.growth-steps,.card-editor-grid{grid-template-columns:1fr}.growth-card{padding:18px}}
`;
 fs.writeFileSync(cssFile,css);
}

function insertBeforeFooter(file,marker,html){
 if(!fs.existsSync(file))return;
 let h=fs.readFileSync(file,'utf8');
 if(h.includes(marker))return;
 h=h.replace(/<footer\b/i,html+'<footer');
 fs.writeFileSync(file,h);
}
const homeAr=`<!-- GROWTH_HOME_AR_V60 --><section class="growth-section soft"><div class="container"><div class="growth-copy"><div class="growth-kicker">من النشاط إلى النمو</div><h2>تسويق متكامل يربط الظهور بالـLeads والإيراد</h2><p>بدل إدارة SEO والإعلانات والمحتوى والمتجر كمهام منفصلة، يتم ربطها بهدف تجاري واحد ومسار قياس واضح. النتيجة: قرارات أسرع، رسائل أكثر اتساقًا، وميزانية تتحرك نحو ما يحقق أثرًا.</p></div><div class="growth-grid"><article class="growth-card"><h3>تشخيص قبل التنفيذ</h3><p>تحديد أكبر فرصة أو تسرب في الرحلة قبل زيادة الإنفاق أو إنتاج محتوى إضافي.</p></article><article class="growth-card"><h3>خطة 90 يومًا</h3><p>أولويات واضحة موزعة بين Quick Wins وأصول طويلة المدى وتجارب قابلة للقياس.</p></article><article class="growth-card"><h3>قياس يهم الإدارة</h3><p>Leads وجودة الفرصة وCAC وROAS والإيراد بدل الاكتفاء بالزيارات والانطباعات.</p></article></div><div class="growth-cta"><a class="btn primary" href="/ar/contact.html">اطلب جلسة تشخيص →</a><a class="btn outline" href="/ar/portfolio.html">شاهد الأعمال</a></div></div></section><section class="growth-section"><div class="container"><div class="growth-kicker">طريقة العمل</div><h2>من المشكلة إلى خطة قابلة للتنفيذ</h2><div class="growth-steps"><div class="growth-step">تشخيص السوق والبيانات</div><div class="growth-step">تحديد الأولويات والـICP</div><div class="growth-step">تنفيذ وقياس التجارب</div><div class="growth-step">توسيع ما ينجح</div></div></div></section>`;
const homeEn=`<!-- GROWTH_HOME_EN_V60 --><section class="growth-section soft"><div class="container"><div class="growth-copy"><div class="growth-kicker">From activity to growth</div><h2>Integrated marketing that connects visibility to leads and revenue</h2><p>SEO, paid media, content and e-commerce should not operate as isolated tasks. They should share one commercial objective and one measurement system.</p></div><div class="growth-grid"><article class="growth-card"><h3>Diagnose before execution</h3><p>Find the biggest growth opportunity or conversion leak before adding spend or content volume.</p></article><article class="growth-card"><h3>A 90-day roadmap</h3><p>Clear priorities across quick wins, compounding assets and measurable experiments.</p></article><article class="growth-card"><h3>Metrics leadership can use</h3><p>Lead quality, CAC, ROAS and revenue—not only traffic and impressions.</p></article></div><div class="growth-cta"><a class="btn primary" href="/en/contact.html">Request a diagnosis →</a><a class="btn outline" href="/en/portfolio.html">View selected work</a></div></div></section><section class="growth-section"><div class="container"><div class="growth-kicker">How I work</div><h2>From problem to executable growth plan</h2><div class="growth-steps"><div class="growth-step">Diagnose market and data</div><div class="growth-step">Prioritise ICP and opportunities</div><div class="growth-step">Execute and measure experiments</div><div class="growth-step">Scale what works</div></div></div></section>`;
insertBeforeFooter(path.join(root,'index.html'),'GROWTH_HOME_AR_V60',homeAr);
insertBeforeFooter(path.join(root,'ar','index.html'),'GROWTH_HOME_AR_V60',homeAr);
insertBeforeFooter(path.join(root,'en','index.html'),'GROWTH_HOME_EN_V60',homeEn);

const aboutAr=`<!-- GROWTH_ABOUT_AR_V60 --><section class="growth-section soft"><div class="container"><div class="growth-copy"><div class="growth-kicker">كيف أضيف قيمة</div><h2>Full-Stack Marketing بعقلية Business First</h2><p>أتعامل مع التسويق كمنظومة: بحث، Paid Media، محتوى، تجارة إلكترونية، تجربة رقمية، فعاليات وقياس. الهدف ليس تشغيل قنوات أكثر، بل اختيار القنوات التي تخدم النمو وربطها ببعضها.</p></div><div class="growth-grid"><article class="growth-card"><h3>استراتيجية</h3><p>ترجمة أهداف الأعمال إلى ICP ورسائل وأولويات وقنوات وخطة تنفيذ.</p></article><article class="growth-card"><h3>تنفيذ</h3><p>القدرة على الانتقال من الخطة إلى SEO وحملات ومحتوى وصفحات وتقارير.</p></article><article class="growth-card"><h3>تحسين مستمر</h3><p>مراجعة البيانات والـfunnel وإعادة توزيع الجهد حسب أثره التجاري.</p></article></div><div class="growth-cta"><a class="btn primary" href="/ar/contact.html">ناقش احتياجك التسويقي →</a></div></div></section>`;
const aboutEn=`<!-- GROWTH_ABOUT_EN_V60 --><section class="growth-section soft"><div class="container"><div class="growth-copy"><div class="growth-kicker">How I create value</div><h2>Full-stack marketing with a business-first mindset</h2><p>I treat marketing as one system across search, paid media, content, e-commerce, digital experience, events and measurement. The goal is not to run more channels; it is to connect the right channels to growth.</p></div><div class="growth-grid"><article class="growth-card"><h3>Strategy</h3><p>Translate business goals into ICP, messaging, priorities, channels and an execution roadmap.</p></article><article class="growth-card"><h3>Execution</h3><p>Move from plan to SEO, campaigns, content, landing pages and reporting.</p></article><article class="growth-card"><h3>Continuous improvement</h3><p>Use funnel and performance data to redirect effort toward commercial impact.</p></article></div><div class="growth-cta"><a class="btn primary" href="/en/contact.html">Discuss your marketing challenge →</a></div></div></section>`;
insertBeforeFooter(path.join(root,'ar','about.html'),'GROWTH_ABOUT_AR_V60',aboutAr);
insertBeforeFooter(path.join(root,'en','about.html'),'GROWTH_ABOUT_EN_V60',aboutEn);

const servicesAr=`<!-- GROWTH_SERVICES_AR_V60 --><section class="growth-section soft"><div class="container"><div class="growth-kicker">نماذج العمل</div><h2>اختر مستوى التدخل المناسب</h2><div class="growth-grid"><article class="growth-card"><h3>Audit & Roadmap</h3><p>للشركات التي تحتاج تشخيصًا مستقلًا وخطة أولويات قبل التنفيذ.</p></article><article class="growth-card"><h3>Growth Sprint</h3><p>تنفيذ مركز لمدة 6–12 أسبوعًا حول هدف واضح مثل SEO أو Paid Media أو CRO.</p></article><article class="growth-card"><h3>Fractional Marketing</h3><p>دعم مستمر يربط الفرق والقنوات والقياس عندما تحتاج قيادة تسويقية مرنة.</p></article></div><div class="growth-faq"><h2>أسئلة شائعة</h2><details><summary>هل أحتاج كل الخدمات معًا؟</summary><p>لا. البداية تكون بالمشكلة ذات الأثر الأكبر، ثم نضيف القنوات عندما تخدم نفس الهدف.</p></details><details><summary>هل يمكن البدء بمراجعة فقط؟</summary><p>نعم. Audit واضح قد يكون أفضل خطوة قبل أي التزام تنفيذي.</p></details><details><summary>كيف يتم قياس النجاح؟</summary><p>نحدد KPI تجاريًا لكل مشروع مثل Qualified Leads أو CAC أو Revenue، ثم نربط المقاييس التشغيلية به.</p></details></div><div class="growth-cta"><a class="btn primary" href="/ar/contact.html">اطلب توصية بالخدمة المناسبة →</a></div></div></section>`;
const servicesEn=`<!-- GROWTH_SERVICES_EN_V60 --><section class="growth-section soft"><div class="container"><div class="growth-kicker">Engagement models</div><h2>Choose the level of support you need</h2><div class="growth-grid"><article class="growth-card"><h3>Audit & Roadmap</h3><p>For teams that need an independent diagnosis and prioritised plan before execution.</p></article><article class="growth-card"><h3>Growth Sprint</h3><p>A focused 6–12 week execution around one outcome such as SEO, paid media or CRO.</p></article><article class="growth-card"><h3>Fractional Marketing</h3><p>Ongoing support connecting teams, channels and measurement when flexible senior marketing support is needed.</p></article></div><div class="growth-faq"><h2>Frequently asked questions</h2><details><summary>Do I need every service?</summary><p>No. Start with the constraint that has the highest commercial impact, then add channels only when they serve the same objective.</p></details><details><summary>Can we start with an audit only?</summary><p>Yes. A clear audit can be the best first step before any execution commitment.</p></details><details><summary>How is success measured?</summary><p>Each engagement starts with a commercial KPI such as qualified leads, CAC or revenue, then connects operational metrics to it.</p></details></div><div class="growth-cta"><a class="btn primary" href="/en/contact.html">Ask which engagement fits →</a></div></div></section>`;
insertBeforeFooter(path.join(root,'ar','services.html'),'GROWTH_SERVICES_AR_V60',servicesAr);
insertBeforeFooter(path.join(root,'en','services.html'),'GROWTH_SERVICES_EN_V60',servicesEn);

const portAr=`<!-- GROWTH_PORT_AR_V60 --><section class="growth-section soft"><div class="container"><div class="growth-copy"><div class="growth-kicker">ما الذي أبحث عنه في كل مشروع؟</div><h2>الأعمال ليست معرض تصميمات؛ هي قرارات مرتبطة بهدف</h2><p>كل Case Study يجب أن تجيب عن أربعة أسئلة: ما المشكلة؟ ما الفرضية؟ ما الذي تم تنفيذه؟ وما المؤشر الذي يثبت أن الاتجاه صحيح؟</p></div><div class="growth-grid"><article class="growth-card"><h3>Context</h3><p>فهم السوق والقيود والقناة قبل اختيار الحل.</p></article><article class="growth-card"><h3>Execution</h3><p>ربط الرسالة والصفحة والحملة والقياس بدل تنفيذ أصل منفصل.</p></article><article class="growth-card"><h3>Learning</h3><p>تسجيل ما نجح وما لم ينجح وتحويله إلى قرار للمرحلة التالية.</p></article></div><div class="growth-cta"><a class="btn primary" href="/ar/contact.html">ناقش مشروعك →</a></div></div></section>`;
const portEn=`<!-- GROWTH_PORT_EN_V60 --><section class="growth-section soft"><div class="container"><div class="growth-copy"><div class="growth-kicker">What I look for in every project</div><h2>Work should show decisions—not just deliverables</h2><p>Every case should answer four questions: what was the problem, what was the hypothesis, what was executed and which signal shows the direction is working?</p></div><div class="growth-grid"><article class="growth-card"><h3>Context</h3><p>Understand market, constraints and channel before choosing the solution.</p></article><article class="growth-card"><h3>Execution</h3><p>Connect message, page, campaign and measurement instead of delivering an isolated asset.</p></article><article class="growth-card"><h3>Learning</h3><p>Capture what worked, what did not and turn that into the next decision.</p></article></div><div class="growth-cta"><a class="btn primary" href="/en/contact.html">Discuss your project →</a></div></div></section>`;
insertBeforeFooter(path.join(root,'ar','portfolio.html'),'GROWTH_PORT_AR_V60',portAr);
insertBeforeFooter(path.join(root,'en','portfolio.html'),'GROWTH_PORT_EN_V60',portEn);

const contactAr=`<!-- GROWTH_CONTACT_AR_V60 --><section class="growth-section soft"><div class="container"><div class="growth-copy"><div class="growth-kicker">ماذا يحدث بعد الإرسال؟</div><h2>محادثة قصيرة لتحديد المشكلة قبل اقتراح الحل</h2></div><div class="growth-steps"><div class="growth-step">أراجع السياق والهدف</div><div class="growth-step">نحدد أكبر أولوية</div><div class="growth-step">أقترح نطاق العمل المناسب</div><div class="growth-step">نحدد الخطوة التالية</div></div><p>للحصول على رد أدق، اذكر الهدف، القنوات الحالية، وأكبر مشكلة تريد حلها.</p></div></section>`;
const contactEn=`<!-- GROWTH_CONTACT_EN_V60 --><section class="growth-section soft"><div class="container"><div class="growth-copy"><div class="growth-kicker">What happens next?</div><h2>A short conversation to define the problem before proposing a solution</h2></div><div class="growth-steps"><div class="growth-step">Review context and objective</div><div class="growth-step">Identify the highest priority</div><div class="growth-step">Recommend the right scope</div><div class="growth-step">Agree the next step</div></div><p>For a more useful response, share your objective, current channels and the biggest issue you want to solve.</p></div></section>`;
insertBeforeFooter(path.join(root,'ar','contact.html'),'GROWTH_CONTACT_AR_V60',contactAr);
insertBeforeFooter(path.join(root,'en','contact.html'),'GROWTH_CONTACT_EN_V60',contactEn);

const siteJsFile=path.join(root,'assets','site.js');
let js=fs.readFileSync(siteJsFile,'utf8');
if(!js.includes('__RASSMIY_CARDS_V60__')){
js+=`
;(()=>{
 if(window.__RASSMIY_CARDS_V60__)return;window.__RASSMIY_CARDS_V60__=true;
 const lang=(document.documentElement.lang||'ar').startsWith('ar')?'ar':'en';
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
 const field=(c,n)=>c[n+'_'+lang]||c[n+'_en']||c[n+'_ar']||'';
 const renderService=(c)=>'<article class="service-card is-clickable-card" data-card-key="'+esc(c.id)+'" data-card-link="'+esc(field(c,'cta_url'))+'">'+(c.image?'<img class="editable-card-media" src="'+esc(c.image)+'" alt="'+esc(field(c,'alt')||field(c,'title'))+'">':'')+(field(c,'eyebrow')?'<div class="card-eyebrow">'+esc(field(c,'eyebrow'))+'</div>':'')+'<h3>'+esc(field(c,'title'))+'</h3><p>'+esc(field(c,'description'))+'</p>'+(field(c,'metric')?'<div class="card-metric">'+esc(field(c,'metric'))+'</div>':'')+(field(c,'cta_label')?'<a class="link" href="'+esc(field(c,'cta_url')||'#')+'">'+esc(field(c,'cta_label'))+'</a>':'')+'</article>';
 const renderCase=(c)=>'<article class="case-card is-clickable-card" data-card-key="'+esc(c.id)+'" data-card-link="'+esc(field(c,'cta_url'))+'">'+(c.image?'<img class="editable-card-media" src="'+esc(c.image)+'" alt="'+esc(field(c,'alt')||field(c,'title'))+'">':'')+(field(c,'eyebrow')?'<div class="card-eyebrow">'+esc(field(c,'eyebrow'))+'</div>':'')+'<h3>'+esc(field(c,'title'))+'</h3><p>'+esc(field(c,'description'))+'</p>'+(field(c,'metric')?'<div class="card-metric">'+esc(field(c,'metric'))+'</div>':'')+(field(c,'cta_label')?'<a class="case-link" href="'+esc(field(c,'cta_url')||'#')+'">'+esc(field(c,'cta_label'))+'</a>':'')+'</article>';
 async function hydrate(){
  try{
   const r=await fetch('/api/cards',{headers:{Accept:'application/json'},cache:'no-store'});if(!r.ok)return;
   const data=await r.json(),cards=(data.cards||[]).filter(c=>c.enabled!==false).sort((a,b)=>(a.order||0)-(b.order||0));
   for(const collection of ['service','portfolio']){
    const selector=collection==='service'?'.service-card':'.case-card';
    const existing=[...document.querySelectorAll(selector)];
    if(!existing.length)continue;
    const parent=existing[0].parentElement;
    const list=cards.filter(c=>c.collection===collection);
    const byId=new Map(list.map(c=>[c.id,c]));
    existing.forEach(el=>{const id=el.dataset.cardKey;if(id&&!byId.has(id))el.hidden=true;});
    for(const c of list){
      const old=document.querySelector(selector+'[data-card-key="'+CSS.escape(c.id)+'"]');
      const wrap=document.createElement('div');wrap.innerHTML=(collection==='service'?renderService(c):renderCase(c));
      const fresh=wrap.firstElementChild;
      if(old)old.replaceWith(fresh);else parent.appendChild(fresh);
    }
   }
   document.dispatchEvent(new CustomEvent('rassmiy:cards-hydrated'));
  }catch(e){console.warn('Cards hydration skipped',e);}
 }
 document.readyState==='loading'?document.addEventListener('DOMContentLoaded',hydrate):hydrate();
})();
`;
fs.writeFileSync(siteJsFile,js);
}

const adminJsFile=path.join(root,'assets','admin.js');
let adminJs=fs.readFileSync(adminJsFile,'utf8');
if(!adminJs.includes('__RASSMIY_CARD_MANAGER_V60__')){
adminJs+=`
;(()=>{
 if(window.__RASSMIY_CARD_MANAGER_V60__)return;window.__RASSMIY_CARD_MANAGER_V60__=true;
 const ar=()=>document.documentElement.dir==='rtl'||(document.documentElement.lang||'ar').startsWith('ar');
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
 let cards=[];
 const labels=()=>ar()?{title:'إدارة الكروت',sub:'تحكم كامل في كروت الخدمات والأعمال: المحتوى والصور والروابط والترتيب والظهور بالعربي والإنجليزي.',add:'إضافة كرت',save:'حفظ كل الكروت',service:'خدمة',portfolio:'عمل / Case Study',proof:'Proof',testimonial:'Testimonial',saved:'تم حفظ الكروت بنجاح.',delete:'حذف',duplicate:'نسخ',up:'أعلى',down:'أسفل'}:{title:'Card Manager',sub:'Full control over service and portfolio cards: content, images, links, order and visibility in Arabic and English.',add:'Add card',save:'Save all cards',service:'Service',portfolio:'Portfolio / Case Study',proof:'Proof',testimonial:'Testimonial',saved:'Cards saved successfully.',delete:'Delete',duplicate:'Duplicate',up:'Up',down:'Down'};
 const input=(label,name,val='',type='text')=>'<label><span>'+label+'</span><input type="'+type+'" data-f="'+name+'" value="'+esc(val)+'"></label>';
 const area=(label,name,val='')=>'<label><span>'+label+'</span><textarea rows="3" data-f="'+name+'">'+esc(val)+'</textarea></label>';
 function renderItem(c,i){
  const L=labels();return '<details class="card-editor-item" data-i="'+i+'" '+(i===0?'open':'')+'><summary>'+(c.collection==='portfolio'?L.portfolio:L.service)+' · '+esc(c.title_ar||c.title_en||c.id)+'</summary><div class="card-editor-grid">'+
   input('ID','id',c.id)+
   '<label><span>Collection</span><select data-f="collection"><option value="service" '+(c.collection==='service'?'selected':'')+'>'+L.service+'</option><option value="portfolio" '+(c.collection==='portfolio'?'selected':'')+'>'+L.portfolio+'</option><option value="proof" '+(c.collection==='proof'?'selected':'')+'>'+L.proof+'</option><option value="testimonial" '+(c.collection==='testimonial'?'selected':'')+'>'+L.testimonial+'</option></select></label>'+
   input('Order','order',c.order||0,'number')+input('Icon','icon',c.icon||'')+input('Image URL / Media Path','image',c.image||'')+
   input('العنوان AR','title_ar',c.title_ar||'')+input('Title EN','title_en',c.title_en||'')+
   area('الوصف AR','description_ar',c.description_ar||'')+area('Description EN','description_en',c.description_en||'')+
   input('Eyebrow AR','eyebrow_ar',c.eyebrow_ar||'')+input('Eyebrow EN','eyebrow_en',c.eyebrow_en||'')+
   input('Metric AR','metric_ar',c.metric_ar||'')+input('Metric EN','metric_en',c.metric_en||'')+
   input('CTA AR','cta_label_ar',c.cta_label_ar||'')+input('CTA EN','cta_label_en',c.cta_label_en||'')+
   input('CTA URL AR','cta_url_ar',c.cta_url_ar||'')+input('CTA URL EN','cta_url_en',c.cta_url_en||'')+
   input('ALT AR','alt_ar',c.alt_ar||'')+input('ALT EN','alt_en',c.alt_en||'')+
   '<label><span>Visible</span><input type="checkbox" data-f="enabled" '+(c.enabled!==false?'checked':'')+'></label></div><div class="card-editor-actions"><button type="button" data-act="up">'+L.up+'</button><button type="button" data-act="down">'+L.down+'</button><button type="button" data-act="duplicate">'+L.duplicate+'</button><button type="button" class="danger" data-act="delete">'+L.delete+'</button></div></details>';
 }
 function syncFromDom(){
  document.querySelectorAll('.card-editor-item').forEach((el,i)=>{const c=cards[i]||{};el.querySelectorAll('[data-f]').forEach(inp=>{const k=inp.dataset.f;c[k]=inp.type==='checkbox'?inp.checked:(k==='order'?Number(inp.value||0):inp.value)});cards[i]=c;});
 }
 function render(){
  const list=document.querySelector('.card-editor-list');if(!list)return;list.innerHTML=cards.map(renderItem).join('');
 }
 async function save(){
  syncFromDom();const csrf=document.querySelector('input[name="csrf"]')?.value;if(!csrf){alert('Missing CSRF token');return;}
  const fd=new FormData();fd.set('csrf',csrf);fd.set('action','save_cards');fd.set('cards_json',JSON.stringify(cards));
  const status=document.querySelector('.card-manager-status');status.textContent=ar()?'جاري الحفظ…':'Saving…';
  const r=await fetch('/admin/action',{method:'POST',body:fd,credentials:'same-origin'});if(!r.ok)throw new Error('Save failed');
  status.textContent=labels().saved;
 }
 async function init(){
  if(!location.pathname.startsWith('/admin'))return;
  const settingsLink=document.querySelector('a[href*="section=settings"]');
  if(settingsLink&&!document.querySelector('[data-cards-nav]')){const a=settingsLink.cloneNode(false);a.textContent=ar()?'الكروت':'Cards';a.href='/admin?section=settings&cards=1#card-manager';a.setAttribute('data-cards-nav','');settingsLink.parentElement?.insertBefore(a,settingsLink);}
  if(!location.search.includes('section=settings'))return;
  const main=document.querySelector('.cms-main');if(!main||document.getElementById('card-manager'))return;
  const L=labels();const section=document.createElement('section');section.className='panel card-manager';section.id='card-manager';
  section.innerHTML='<div class="panel-head"><div><h2>'+L.title+'</h2><p>'+L.sub+'</p></div></div><div class="card-manager-toolbar"><button type="button" class="secondary-btn" data-add-card>'+L.add+'</button><button type="button" class="primary-btn" data-save-cards>'+L.save+'</button></div><div class="card-editor-list"></div><p class="card-manager-status"></p>';
  main.appendChild(section);
  try{const r=await fetch('/api/cards',{cache:'no-store'});const d=await r.json();cards=Array.isArray(d.cards)?d.cards:[];}catch{cards=[];}
  render();
  section.addEventListener('input',e=>{if(e.target.matches('[data-f]'))syncFromDom()});
  section.addEventListener('click',e=>{
    const btn=e.target.closest('button');if(!btn)return;
    if(btn.matches('[data-add-card]')){syncFromDom();cards.push({id:'card-'+Date.now(),collection:'service',order:(cards.length+1)*10,enabled:true,title_ar:'كرت جديد',title_en:'New card'});render();return;}
    if(btn.matches('[data-save-cards]')){save().catch(err=>{document.querySelector('.card-manager-status').textContent=err.message});return;}
    const item=btn.closest('.card-editor-item');if(!item)return;syncFromDom();const i=Number(item.dataset.i),act=btn.dataset.act;
    if(act==='delete')cards.splice(i,1);
    if(act==='duplicate')cards.splice(i+1,0,{...cards[i],id:cards[i].id+'-copy-'+Date.now()});
    if(act==='up'&&i>0)[cards[i-1],cards[i]]=[cards[i],cards[i-1]];
    if(act==='down'&&i<cards.length-1)[cards[i+1],cards[i]]=[cards[i],cards[i+1]];
    cards.forEach((c,j)=>c.order=(j+1)*10);render();
  });
  if(new URLSearchParams(location.search).get('cards')==='1')setTimeout(()=>section.scrollIntoView({behavior:'smooth'}),100);
 }
 document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();
`;
fs.writeFileSync(adminJsFile,adminJs);
}


/* STATIC_GROWTH_PAGES_V61 */
const escapeHtml=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]));
function publicLayout(lang,{title,meta,canonical,alt,body,type='website',schema=''}){
 const ar=lang==='ar',home=ar?'/':'/en/index.html';
 const nav=`<header class="topbar"><div class="container nav"><a class="brand" href="${home}"><img src="/assets/logo.jpg" alt="Rassmiy Marketing"><span class="brand-copy"><b>RASSMIY</b><span>MARKETING</span></span></a><nav class="menu"><a href="${home}">${ar?'الرئيسية':'Home'}</a><a href="/${lang}/about.html">${ar?'من أنا':'About'}</a><a href="/${lang}/services.html">${ar?'الخدمات':'Services'}</a><a href="/${lang}/portfolio.html">${ar?'الأعمال':'Portfolio'}</a><a href="/${lang}/articles">${ar?'المقالات':'Articles'}</a><a href="/${lang}/contact.html">${ar?'تواصل':'Contact'}</a></nav><div class="nav-actions"><a class="lang" href="${alt}">${ar?'EN':'AR'}</a><a class="btn primary desktop-action" href="/${lang}/contact.html">${ar?'طلب استشارة →':'Book a consultation →'}</a><button class="mobile-toggle" type="button" aria-label="${ar?'فتح القائمة':'Open menu'}" aria-expanded="false" data-public-menu-toggle>☰</button></div></div></header>`;
 const footer=`<footer><div class="container footer-grid"><div><b>RASSMIY MARKETING</b><p>${ar?'استراتيجية، تنفيذ وقياس للنمو.':'Strategy, execution and measurement for growth.'}</p></div><div class="social-contact"><a href="mailto:mohamed.rassmiy@gmail.com">mohamed.rassmiy@gmail.com</a><a href="https://wa.me/966536741442">WhatsApp</a><a href="https://www.linkedin.com/company/rassmiy-marketing/" target="_blank" rel="noopener noreferrer">LinkedIn</a></div></div></footer>`;
 return `<!doctype html><html lang="${lang}" dir="${ar?'rtl':'ltr'}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(title)}</title><meta name="description" content="${escapeHtml(meta)}"><meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1"><link rel="canonical" href="${escapeHtml(canonical)}"><link rel="alternate" hreflang="${lang}" href="${escapeHtml(canonical)}"><link rel="alternate" hreflang="${ar?'en':'ar'}" href="${escapeHtml(alt)}"><link rel="alternate" hreflang="x-default" href="${escapeHtml(alt)}"><meta property="og:title" content="${escapeHtml(title)}"><meta property="og:description" content="${escapeHtml(meta)}"><meta property="og:url" content="${escapeHtml(canonical)}"><meta property="og:type" content="${type}"><link rel="icon" href="/favicon"><link rel="stylesheet" href="/assets/styles.css">${schema?`<script type="application/ld+json">${schema}</script>`:''}</head><body>${nav}${body}${footer}<script defer src="/assets/site.js"></script></body></html>`;
}
const siteBase='https://rassmiy-marketing.netlify.app';
for(const p of PAGES){
 for(const lang of ['ar','en']){
  const ar=lang==='ar',slug=ar?p.slug_ar:p.slug_en,otherSlug=ar?p.slug_en:p.slug_ar;
  const canonical=siteBase+'/'+lang+'/pages/'+encodeURIComponent(slug),alt=siteBase+'/'+(ar?'en':'ar')+'/pages/'+encodeURIComponent(otherSlug);
  const title=ar?p.seo_title_ar:p.seo_title_en,meta=ar?p.meta_description_ar:p.meta_description_en;
  const h1=ar?p.title_ar:p.title_en,desc=ar?p.short_description_ar:p.short_description_en,content=ar?p.content_ar:p.content_en;
  const body=`<section class="page-hero"><div class="container"><div class="kicker">${ar?'استشارات نمو':'Growth Consulting'}</div><h1>${h1}</h1><p>${desc}</p><div class="hero-ctas"><a class="btn primary" href="/${lang}/contact.html">${ar?'اطلب استشارة →':'Request a consultation →'}</a><a class="btn outline" href="/${lang}/portfolio.html">${ar?'شاهد الأعمال':'View work'}</a></div></div></section><section class="section"><div class="container"><article class="prose">${content}</article></div></section>`;
  const dir=path.join(root,lang,'pages',slug);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'index.html'),publicLayout(lang,{title,meta,canonical,alt,body,type:'website'}));
 }
}
function articleCard(lang,a){
 const ar=lang==='ar',slug=ar?a.slug_ar:a.slug_en,title=ar?a.title_ar:a.title_en,desc=ar?a.short_description_ar:a.short_description_en;
 return `<article class="article-card"><div class="tag">${escapeHtml(a.category||'Growth')}</div><h2><a href="/${lang}/articles/${encodeURIComponent(slug)}">${escapeHtml(title)}</a></h2><p>${escapeHtml(desc)}</p><a class="link" href="/${lang}/articles/${encodeURIComponent(slug)}">${ar?'اقرأ المقال →':'Read article →'}</a></article>`;
}
for(const lang of ['ar','en']){
 const ar=lang==='ar';
 const cards=ARTICLES.map(a=>articleCard(lang,a)).join('');
 const indexBody=`<section class="page-hero"><div class="container"><div class="kicker">${ar?'المقالات':'Articles'}</div><h1>${ar?'محتوى عملي للتسويق والنمو':'Practical marketing and growth insights'}</h1><p>${ar?'SEO وAEO وGEO والإعلانات والتجارة الإلكترونية وLead Generation — بهدف تحويل المعرفة إلى قرار وتنفيذ.':'SEO, AEO, GEO, paid media, e-commerce and lead generation—built to turn insight into action.'}</p></div></section><section class="section soft"><div class="container"><div class="articles">${cards}</div></div></section>`;
 const indexDir=path.join(root,lang,'articles');fs.mkdirSync(indexDir,{recursive:true});
 fs.writeFileSync(path.join(indexDir,'index.html'),publicLayout(lang,{title:ar?'مقالات التسويق والنمو | Rassmiy Marketing':'Marketing & Growth Articles | Rassmiy Marketing',meta:ar?'مقالات عملية عن SEO والإعلانات والتجارة الإلكترونية وLead Generation في السعودية.':'Practical articles on SEO, paid media, e-commerce and lead generation for Saudi businesses.',canonical:siteBase+'/'+lang+'/articles',alt:siteBase+'/'+(ar?'en':'ar')+'/articles',body:indexBody,type:'website'}));
 for(const a of ARTICLES){
  const slug=ar?a.slug_ar:a.slug_en,otherSlug=ar?a.slug_en:a.slug_ar,title=ar?a.seo_title_ar:a.seo_title_en,meta=ar?a.meta_description_ar:a.meta_description_en,headline=ar?a.title_ar:a.title_en,desc=ar?a.short_description_ar:a.short_description_en,content=ar?a.content_ar:a.content_en,ctaTitle=ar?a.cta_title_ar:a.cta_title_en,ctaText=ar?a.cta_text_ar:a.cta_text_en,ctaBtn=ar?a.cta_button_ar:a.cta_button_en,ctaUrl=ar?a.cta_url_ar:a.cta_url_en;
  const canonical=siteBase+'/'+lang+'/articles/'+encodeURIComponent(slug),alt=siteBase+'/'+(ar?'en':'ar')+'/articles/'+encodeURIComponent(otherSlug);
  const schema=JSON.stringify({'@context':'https://schema.org','@type':'Article',headline:headline,description:desc,datePublished:a.published_at,author:{'@type':'Person',name:'Mohamed Ali Rassmiy'},publisher:{'@type':'Organization',name:'Rassmiy Marketing'}});
  const body=`<section class="page-hero"><div class="container"><div class="kicker">${escapeHtml(a.category||'Growth')}</div><h1>${headline}</h1><p>${desc}</p></div></section><section class="section"><div class="container"><article class="prose">${content}</article><aside class="growth-card"><h2>${ctaTitle}</h2><p>${ctaText}</p><a class="btn primary" href="${ctaUrl}">${ctaBtn}</a></aside></div></section>`;
  const dir=path.join(root,lang,'articles',slug);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'index.html'),publicLayout(lang,{title,meta,canonical,alt,body,type:'article',schema}));
 }
}
const growthUrls=[];
for(const p of PAGES)for(const lang of ['ar','en'])growthUrls.push(siteBase+'/'+lang+'/pages/'+encodeURIComponent(lang==='ar'?p.slug_ar:p.slug_en));
growthUrls.push(siteBase+'/ar/articles',siteBase+'/en/articles');
for(const a of ARTICLES)for(const lang of ['ar','en'])growthUrls.push(siteBase+'/'+lang+'/articles/'+encodeURIComponent(lang==='ar'?a.slug_ar:a.slug_en));
fs.writeFileSync(path.join(root,'growth-urls-v61.json'),JSON.stringify(growthUrls,null,2));

fs.writeFileSync(path.join(root,'growth-v60.json'),JSON.stringify({cards:CARDS,pages:PAGES.map(x=>x.id),articles:ARTICLES.map(x=>x.id)},null,2));
