import fs from 'node:fs';
const root=process.argv[2]||'release',file=`${root}/netlify/functions/app.mjs`;
let s=fs.readFileSync(file,'utf8');
function change(a,b){if(!s.includes(a))throw new Error('Hardening anchor missing: '+a.slice(0,90));s=s.replace(a,b);}
s="import sanitizeHtml from 'sanitize-html';\n"+s;
s+=String.raw`
// SECURITY_HARDENING_V67
function cleanContent(value){return sanitizeHtml(String(value||''),{allowedTags:[...sanitizeHtml.defaults.allowedTags,'img','figure','figcaption'],allowedAttributes:{...sanitizeHtml.defaults.allowedAttributes,'*':['class'],img:['src','alt','width','height','loading'],a:['href','name','target','rel']},allowedSchemes:['http','https','mailto','tel'],allowProtocolRelative:false,transformTags:{a:(tagName,attribs)=>({tagName,attribs:{...attribs,rel:'noopener noreferrer'}})}});}
function safeCardUrl(value,image=false){const u=String(value||'').trim();if(!u)return '';if(/[\u0000-\u0020<>]/.test(u)||u.startsWith('//')||u.includes('\\'))throw new Error('Invalid card URL');if(u.startsWith('/')||(!image&&u.startsWith('#')))return u;const parsed=new URL(u);if(!['https:','http:',...(!image?['mailto:','tel:']:[])].includes(parsed.protocol))throw new Error('Unsupported URL scheme');return u;}
function publicCards(cards){return cards.map(c=>{const x={...c};for(const key of ['image','cta_url_ar','cta_url_en']){try{x[key]=safeCardUrl(x[key],key==='image')}catch{x[key]=''}}return x});}
function consentHead(value){return String(value||'').replace(/<script\b([^>]*)>/gi,(_,attrs)=>'<script type="text/plain" data-cookie-category="analytics"'+attrs.replace(/\s+type\s*=\s*(?:"[^"]*"|'[^']*'|[^\s>]+)/gi,'')+'>');}
`;
change("if(i>0) out[part.slice(0,i).trim()]=decodeURIComponent(part.slice(i+1).trim());","if(i>0){try{out[part.slice(0,i).trim()]=decodeURIComponent(part.slice(i+1).trim())}catch{}}");
change("const f=formToObject(await req.formData()); if(checkCsrf(session,f)&&isAdmin(session))logActivity", "const f=formToObject(await req.formData()); if(!checkCsrf(session,f))return saveAnd(html('Invalid CSRF token',419)); if(isAdmin(session))logActivity");
change("const from=String(f.from||'').trim(), to=String(f.to||'').trim();", "const from=String(f.from||'').trim(), to=safeCardUrl(f.to||'');");
change('state.settings.cards_json=JSON.stringify(cards);','for(const card of cards){card.image=safeCardUrl(card.image,true);card.cta_url_ar=safeCardUrl(card.cta_url_ar);card.cta_url_en=safeCardUrl(card.cta_url_en);} state.settings.cards_json=JSON.stringify(cards);');
change("cards.sort((a,b)=>Number(a.order||0)-Number(b.order||0)); return new Response(JSON.stringify({cards})", "cards=publicCards(cards); cards.sort((a,b)=>Number(a.order||0)-Number(b.order||0)); return new Response(JSON.stringify({cards})");
change("async function loadState(...args){return revealStateV62(await loadStateRaw(...args));}", "async function loadState(...args){const state=await revealStateV62(await loadStateRaw(...args));for(const row of [...(state.pages||[]),...(state.articles||[])])for(const key of ['content','content_ar','content_en'])if(row[key])row[key]=cleanContent(row[key]);return state;}");
s=s.replaceAll("content_ar:f.content_ar||''", "content_ar:cleanContent(f.content_ar)").replaceAll("content_en:f.content_en||''", "content_en:cleanContent(f.content_en)");
change("${state.settings.global_head_code||''}", "${consentHead(state.settings.global_head_code)}");
change("try{ JSON.parse(v); return v; }catch{return '';}", "try{ JSON.parse(v); return String(v).replaceAll('<','\\u003c'); }catch{return '';}");
const lead="const name=String(f.name||'').trim(); if(!name)return saveAnd(text('Name is required',400));";
change(lead, "const name=String(f.name||'').trim(); if(!name)return saveAnd(text('Name is required',400)); if(name.length>180||String(f.message||'').length>10000||String(f.email||'').length>254||String(f.phone||'').length>80||String(f.company||'').length>250||String(f.source||'').length>250||String(f.page_url||'').length>500)return saveAnd(text('Form fields exceed allowed size',400)); if(f.email&&!/^\\S+@\\S+\\.\\S+$/.test(f.email))return saveAnd(text('Invalid email',400));");
fs.writeFileSync(file,s);
// Viewport harness uses real same-origin iframe viewports for CSS and navigation checks.
fs.writeFileSync(`${root}/responsive-preview.html`,String.raw`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Responsive Preview</title><style>body{font:16px system-ui;margin:20px;background:#edf2f7;color:#15334f}button,select{font:inherit;padding:10px;margin:4px}button[aria-pressed=true]{background:#15334f;color:white}.viewport{overflow:auto;margin-top:16px}iframe{border:1px solid #aab8c6;background:white;display:block}#result{padding:10px}</style></head><body><h1>Mobile & Tablet Preview</h1><p>CSS viewport simulation. Device hardware and touch gestures require a device check.</p><select aria-label="Page"><option value="/ar/index.html">Arabic Home</option><option value="/en/index.html">English Home</option><option value="/ar/portfolio.html">Arabic Portfolio</option><option value="/en/portfolio.html">English Portfolio</option><option value="/ar/contact.html">Arabic Contact</option><option value="/en/contact.html">English Contact</option><option value="/ar/services.html">Arabic Services</option><option value="/en/services.html">English Services</option><option value="/admin">Admin Dashboard</option></select><button data-width="390" aria-pressed="true">Mobile 390</button><button data-width="768" aria-pressed="false">Tablet 768</button><button data-width="1024" aria-pressed="false">Tablet 1024</button><button id="measure">Check layout</button><div id="result" role="status"></div><div class="viewport"><iframe title="Website viewport" src="/ar/index.html" width="390" height="900"></iframe></div><script>const frame=document.querySelector('iframe');document.querySelector('select').onchange=e=>frame.src=e.target.value;for(const b of document.querySelectorAll('[data-width]'))b.onclick=()=>{frame.width=b.dataset.width;for(const other of document.querySelectorAll('[data-width]'))other.setAttribute('aria-pressed',String(other===b));};document.querySelector('#measure').onclick=()=>{const d=frame.contentDocument,w=frame.contentWindow;document.querySelector('#result').textContent=JSON.stringify({viewport:w.innerWidth,documentWidth:d.documentElement.scrollWidth,overflow:d.documentElement.scrollWidth>w.innerWidth,failedImages:[...d.images].filter(i=>i.complete&&!i.naturalWidth).map(i=>i.getAttribute('src'))});};</script></body></html>`);
function walk(dir){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(x=>x.isDirectory()?walk(`${dir}/${x.name}`):[`${dir}/${x.name}`]);}
for(const f of walk(root).filter(f=>f.endsWith('.html'))){let h=fs.readFileSync(f,'utf8');if(/name="robots"[^>]+noindex/.test(h)||!h.includes('</footer>'))continue;const ar=/lang="ar"/.test(h);if(!/<meta\s+name=["']robots["']/.test(h))h=h.replace('</head>','<meta name="robots" content="index,follow,max-image-preview:large"></head>');if(!h.includes('linkedin.com/company/rassmiy-marketing/'))h=h.replace('</footer>',`<div class="container social-contact"><a href="https://www.linkedin.com/company/rassmiy-marketing/" target="_blank" rel="noopener noreferrer">Rassmiy Marketing · LinkedIn</a></div></footer>`);if(!h.includes('linkedin.com/in/mohamedrassmiy'))h=h.replace('</footer>',`<div class="container social-contact"><a href="https://www.linkedin.com/in/mohamedrassmiy" target="_blank" rel="noopener noreferrer">${ar?'حسابي الشخصي على LinkedIn':'My LinkedIn profile'}</a></div></footer>`);if(!h.includes('class="whatsapp-floating"'))h=h.replace('</body>',`<a class="whatsapp-floating" href="https://wa.me/966536741442" target="_blank" rel="noopener noreferrer">${ar?'واتساب':'WhatsApp'}</a></body>`);fs.writeFileSync(f,h);}
function divContent(h,className){const start=h.indexOf(`<div class="${className}">`);if(start<0)return null;const body=start+`<div class="${className}">`.length;const tokens=/<div\b[^>]*>|<\/div>/gi;tokens.lastIndex=body;let depth=1,m;while((m=tokens.exec(h))){depth+=m[0].startsWith('</')?-1:1;if(!depth)return {start:body,end:m.index};}throw new Error('Unbalanced HTML section');}
for(const lang of ['ar','en']){const index=fs.readFileSync(`${root}/${lang}/articles/index.html`,'utf8');const section=divContent(index,'articles');const cards=index.slice(section.start,section.end).match(/<article\b[\s\S]*?<\/article>/g)?.slice(0,6).join('')||'';for(const file of [`${root}/${lang}/index.html`,...(lang==='ar'?[`${root}/index.html`]:[])]){let h=fs.readFileSync(file,'utf8');const old=divContent(h,'articles');if(old)h=h.slice(0,old.start)+cards+h.slice(old.end);h=h.replace(/<small>(نمو الزيارات|Traffic Growth)<\/small><strong class="up">\+215%<\/strong>/g,`<small>${lang==='ar'?'القياس':'Measurement'}</small><strong>GA4 / GTM</strong>`).replace(/<small>(العملاء المحتملون|Leads)<\/small><strong class="up">\+340%<\/strong>/g,`<small>${lang==='ar'?'فرص الأعمال':'Business pipeline'}</small><strong>Lead Generation</strong>`).replace('<strong>#1</strong>','<strong>SEO / AEO</strong>').replace('<strong>4.8x</strong>','<strong>CAC / ROAS</strong>');fs.writeFileSync(file,h);}}
