import fs from 'node:fs';
const file=process.argv[2];
if(!file) throw new Error('Target function file is required.');
let s=fs.readFileSync(file,'utf8');
const must=(a,b,label)=>{if(!s.includes(a)) throw new Error('GSC patch failed: '+label); s=s.replace(a,b);};

must("  gtm_id: '',\n", "  gtm_id: '',\n  google_site_verification: '',\n  google_verification_filename: '',\n  google_verification_content: '',\n", 'settings defaults');

must("  const schema=jsonSafe(row.schema_json||''); const globalSchema=jsonSafe(state.settings.global_schema||'');",
     "  const schema=jsonSafe(row.schema_json||''); const globalSchema=jsonSafe(state.settings.global_schema||''); const googleVerify=String(state.settings.google_site_verification||'').trim();", 'head vars');

must('<link rel="canonical" href="${attr(canonical)}"><meta property="og:title"',
     '<link rel="canonical" href="${attr(canonical)}">${googleVerify?`<meta name="google-site-verification" content="${attr(googleVerify)}">`:\'\'}<meta property="og:title"', 'meta tag');

const helper = "function normalizeGoogleVerification(value='') { const raw=String(value||'').trim(); if(!raw)return ''; const m=raw.match(/<meta[^>]+name=[\\\"']google-site-verification[\\\"'][^>]+content=[\\\"']([^\\\"']+)[\\\"']/i)||raw.match(/<meta[^>]+content=[\\\"']([^\\\"']+)[\\\"'][^>]+name=[\\\"']google-site-verification[\\\"']/i); return (m?.[1]||raw).trim(); }\n\n";
must('function adminContent(state,session,url){', helper+'function adminContent(state,session,url){', 'normalizer');

const oldSettings = "  if(section==='settings'){ const s=state.settings; return [section,`${pageHeader('إعدادات الموقع','هوية الموقع وبيانات التواصل — منفصلة عن Global SEO.')}<section class=\"panel narrow\"><form method=\"post\" action=\"/admin/action\">${csrfInput(session)}<input type=\"hidden\" name=\"action\" value=\"save_site_settings\"><div class=\"form-grid two\">${field('Site Name','site_name',s.site_name)}${field('Site URL','site_url',s.site_url,'url')}${field('Contact Email','contact_email',s.contact_email,'email')}${field('Location','location',s.location)}</div>${field('Brand Tagline','brand_tagline',s.brand_tagline||'')}${selectField('Timezone','timezone',s.timezone||'Asia/Riyadh',[['Asia/Riyadh','Asia/Riyadh'],['UTC','UTC'],['Asia/Dubai','Asia/Dubai']])}${field('Favicon Path / URL','favicon_path',s.favicon_path,'text','list=\"media-paths\"')}${mediaDatalist(state)}<button class=\"primary-btn\" type=\"submit\">حفظ إعدادات الموقع</button></form></section>`]; }";
const newSettings = "  if(section==='settings'){ const s=state.settings; const googleFile=s.google_verification_filename||''; return [section,`${pageHeader('إعدادات الموقع','هوية الموقع وبيانات التواصل — منفصلة عن Global SEO.')}<section class=\"panel narrow\"><form method=\"post\" action=\"/admin/action\">${csrfInput(session)}<input type=\"hidden\" name=\"action\" value=\"save_site_settings\"><div class=\"form-grid two\">${field('Site Name','site_name',s.site_name)}${field('Site URL','site_url',s.site_url,'url')}${field('Contact Email','contact_email',s.contact_email,'email')}${field('Location','location',s.location)}</div>${field('Brand Tagline','brand_tagline',s.brand_tagline||'')}${selectField('Timezone','timezone',s.timezone||'Asia/Riyadh',[['Asia/Riyadh','Asia/Riyadh'],['UTC','UTC'],['Asia/Dubai','Asia/Dubai']])}${field('Favicon Path / URL','favicon_path',s.favicon_path,'text','list=\"media-paths\"')}${mediaDatalist(state)}<button class=\"primary-btn\" type=\"submit\">حفظ إعدادات الموقع</button></form></section><section class=\"panel narrow\"><div class=\"panel-head\"><div><h2>Google Search Console</h2><p>ربط الموقع عبر Google HTML Tag أو ملف التحقق الرسمي.</p></div><a class=\"secondary-btn\" target=\"_blank\" rel=\"noopener\" href=\"https://search.google.com/search-console\">فتح Search Console ↗</a></div><form method=\"post\" action=\"/admin/action\" enctype=\"multipart/form-data\">${csrfInput(session)}<input type=\"hidden\" name=\"action\" value=\"save_search_console\">${field('Google verification code / meta tag','google_site_verification',s.google_site_verification||'','text','placeholder=\"ضع قيمة content أو الصق Meta Tag كاملًا\"','يمكنك لصق قيمة verification فقط أو وسم Google Meta Tag كاملًا.')}<label class=\"field\"><span>رفع ملف Google HTML</span><input type=\"file\" name=\"google_verification_file\" accept=\".html,text/html\"><small>ارفع الملف الذي تم تنزيله من Google مثل googlexxxxxxxx.html.</small></label>${googleFile?`<div class=\"verification-status\"><span class=\"check-ok\">✓ ملف التحقق محفوظ</span><a target=\"_blank\" href=\"/${attr(googleFile)}\">/${esc(googleFile)} ↗</a><label class=\"check-field\"><input type=\"checkbox\" name=\"remove_google_file\" value=\"1\"> حذف ملف التحقق الحالي</label></div>`:'<p class=\"muted\">لا يوجد ملف Google HTML محفوظ حاليًا.</p>'}<button class=\"primary-btn\" type=\"submit\">حفظ إعدادات Search Console</button></form><p class=\"muted\"><b>الأفضل للموقع الحالي:</b> رفع ملف HTML لأنه يعمل مباشرة من جذر الدومين. Meta Tag يُضاف تلقائيًا إلى صفحات CMS الديناميكية.</p></section>`]; }";
must(oldSettings,newSettings,'settings UI');

must("async function handleAdminAction(req,state,session){\n  const f=formToObject(await req.formData()); if(!checkCsrf(session,f)) return html('Invalid CSRF token',419); const action=f.action||'';",
     "async function handleAdminAction(req,state,session){\n  const fd=await req.formData(); const f=formToObject(fd); if(!checkCsrf(session,f)) return html('Invalid CSRF token',419); const action=f.action||'';", 'multipart form');

const saveSite="    if(action==='save_site_settings'){ requirePermission(state,session,'settings'); for(const k of ['site_name','site_url','contact_email','location','favicon_path','brand_tagline','timezone']) state.settings[k]=f[k]||''; logActivity(state,session,'Updated','settings','Site settings'); await saveState(state); return redirect(flashUrl('/admin?section=settings','تم حفظ إعدادات الموقع.')); }\n";
const saveGsc="    if(action==='save_search_console'){ requirePermission(state,session,'settings'); state.settings.google_site_verification=normalizeGoogleVerification(f.google_site_verification||''); if(f.remove_google_file){ state.settings.google_verification_filename=''; state.settings.google_verification_content=''; } const file=fd.get('google_verification_file'); if(file&&typeof file.text==='function'&&Number(file.size)>0){ const name=String(file.name||'').trim(); if(!/^google[a-zA-Z0-9_-]+\\.html$/.test(name)) throw new Error('ملف Google يجب أن يكون باسم googlexxxxxxxx.html كما تم تنزيله من Search Console.'); if(Number(file.size)>200*1024) throw new Error('ملف التحقق أكبر من الحجم المتوقع.'); const content=await file.text(); if(!/google-site-verification/i.test(content)) throw new Error('محتوى الملف لا يبدو ملف تحقق صالحًا من Google.'); state.settings.google_verification_filename=name; state.settings.google_verification_content=content; } logActivity(state,session,'Updated','settings','Google Search Console'); await saveState(state); return redirect(flashUrl('/admin?section=settings','تم حفظ إعدادات Google Search Console.')); }\n";
must(saveSite,saveSite+saveGsc,'save action');
must("save_site_settings:'settings',save_seo_settings", "save_site_settings:'settings',save_search_console:'settings',save_seo_settings", 'error map');
must("  if(path==='/robots.txt'){", "  if(state.settings.google_verification_filename && path===`/${state.settings.google_verification_filename}`){ return saveAnd(text(state.settings.google_verification_content||'',200,'text/html; charset=utf-8',{'Cache-Control':'no-store','X-Robots-Tag':'noindex'})); }\n  if(path==='/robots.txt'){", 'file route');

fs.writeFileSync(file,s);
